<?php
    namespace SJD\gestao;

    include_once($_SERVER['DOCUMENT_ROOT']."/SJD/php/initial_loads.php");

?>
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SisJD - Gestao de Acessos</title>
    <link href="/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link href="/sjd/css/1.0/estilos.css" rel="stylesheet">
    <script type="text/javascript" src="/sjd/javascript/polyfill.js"></script>
    <script type="text/javascript" src="/jquery/3.6.0/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <script type="module" src="/sjd/javascript/modulos/ModuloPrincipal.js?2.00"></script>
</head>
<body>
   <main style="display: block;">
      <div class="container-fluid p-0 m-0">
         <div class="row p-0 m-0">
             <div class="col p-0 m-0">
                <div id="barra_superior" class="barra_superior bg-dark text-white text-center text-uppercase fw-bolder position-relative">                              
                    <text class="position-absolute top-50 start-50 translate-middle">
                        Gestao de Acessos
                    </text>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div name="div_pagina" class="div_pagina container-fluid" style="width: 100%; min-width: 100%; inset: 50px 0px 0px;">
                    <div name="div_grid_linha_corpo_pagina" class="row">
                        <div name="div_grid_col_corpo_pagina" class="col">
                            <div name="div_conteudo_pagina" class="div_conteudo_pagina container-fluid _0_1926303068232743 _0_2380883782832114">
                                <div></div>
                                <div name="div_gestao" class="div_gestao container-fluid corpo-conteudo" ajuda_elemento="Veja aqui quem acessou o sistema, quando acesso e qual funcionalidade acessou!" data-tit_aba="gestao" data-nome="gestao">
                                <div class="div_opcoes_pesquisa_l1 row" titulo="Opcoes de Pesquisa" height="25px">
                                    <div class="div_opcoes_pesquisa m-1 col">
                                        <div class="accordion">
                                            <div titulo="Opcoes de Pesquisa" target="#painel_div_opcoes_pesquisa_corpo" class="accordion-item" aberto="1">
                                            <div class="accordion-header" titulo="Opcoes de Pesquisa" target="#painel_div_opcoes_pesquisa_corpo" aberto="1">
                                                <div data-bs-toggle="collapse" data-bs-target="#painel_div_opcoes_pesquisa_corpo" aberto="1" class="accordion-button" type="button" aria-expanded="true" aria-controls="painel_div_opcoes_pesquisa_corpo">Opcoes de Pesquisa</div>
                                            </div>
                                            <div id="painel_div_opcoes_pesquisa_corpo" class="collapse show">
                                                <div class="accordion-body" aberto="1">
                                                    <div class="div_opcoes_pesquisa_simples row">
                                                        <div class="div_opcoes_pesquisa_simples_col col">
                                                        <div class="accordion">
                                                            <div class="div_periodos accordion-item" titulo="Periodos" target="#periodos" aberto="1">
                                                                <div class="accordion-header" titulo="Periodos" target="#periodos" aberto="1">
                                                                    <div data-bs-toggle="collapse" data-bs-target="#periodos" aberto="1" class="accordion-button" type="button" aria-expanded="true" aria-controls="periodos">Periodos</div>
                                                                </div>
                                                                <div id="periodos" class="collapse show">
                                                                    <div class="accordion-body" aberto="1">
                                                                    <div class="row">
                                                                        <div class="col-auto mt-2 div_periodo col">
                                                                            <div dtini="2022-01-01" dtfim="2022-01-24" funcao_inclusao="window.fnsisjd.inserir_periodo_pesquisa({elemento:this})" funcao_exclusao="window.fnsisjd.deletar_controles({elemento:this})" class="card">
                                                                                <div class="card-header">Periodo 01</div>
                                                                                <div class="card-body">
                                                                                <div class="row">
                                                                                    <div class="col">
                                                                                        <div class="row">
                                                                                            <div class="col-auto col"><input type="date" class="componente_data" value="2022-01-01"></div>
                                                                                            <div class="col-auto col"><input type="date" class="componente_data" value="2022-01-24"></div>
                                                                                        </div>
                                                                                        <div class="align-items-center row">
                                                                                            <div class="col">
                                                                                            <div class="w-100 text-center"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/JAN.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/FEV.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/MAR.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/ABR.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/MAI.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/JUN.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/JUL.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/AGO.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/SET.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/OUT.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/NOV.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/DEZ.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><input type="number" class="inputano" value="2021" title="Ano para preenchimento do mes inteiro" step="1" min="0"></div>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="div_opcao_controles_btns_img col-md-auto w-auto"></div>
                                                                                </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="avancado div_avancado accordion-item" titulo="Avancado" target="#avancada">
                                                                <div class="accordion-header" titulo="Avancado" target="#avancada">
                                                                    <div data-bs-toggle="collapse" data-bs-target="#avancada" class="accordion-button collapsed" type="button" aria-expanded="false" aria-controls="avancada">Avancado</div>
                                                                </div>
                                                                <div id="avancada" class="collapse">
                                                                    <div class="accordion-body">
                                                                    <div class="div_opcoes_pesquisa_avancada row">
                                                                        <div class="div_opcoes_pesquisa_avancada_col col">
                                                                            <div class="accordion">
                                                                                <div class="div_condicionantes accordion-item" titulo="Condicionantes" target="#painel_condicionantes">
                                                                                <div class="accordion-header" titulo="Condicionantes" target="#painel_condicionantes">
                                                                                    <div data-bs-toggle="collapse" data-bs-target="#painel_condicionantes" class="accordion-button collapsed" type="button" aria-expanded="false" aria-controls="painel_condicionantes">Condicionantes</div>
                                                                                </div>
                                                                                <div id="painel_condicionantes" class="collapse">
                                                                                    <div class="accordion-body">
                                                                                        <div class="row">
                                                                                            <div class="col-auto mt-2 div_condicionante">
                                                                                            <div type="condicionantes" label="Condicionante 01" visao="Rca" funcao_inclusao="window.fnsisjd.inserir_condicionante_pesquisa({elemento:this})" funcao_exclusao="window.fnsisjd.deletar_controles({elemento:this})" permite_selecao="1" class="card">
                                                                                                <div class="card-header">Condicionante 1</div>
                                                                                                <div class="card-body">
                                                                                                    <div class="row">
                                                                                                        <div class="col">
                                                                                                        <div class="col-auto mt-2 div_condicionante">
                                                                                                            <div type="condicionantes" label="Condicionante 01" visao="Rca" titulo="Condicionante 1" funcao_inclusao="window.fnsisjd.inserir_condicionante_pesquisa({elemento:this})" funcao_exclusao="window.fnsisjd.deletar_controles({elemento:this})" permite_selecao="1" class="div_condicionante">
                                                                                                                <div class="row">
                                                                                                                    <div class="col-auto">
                                                                                                                    <div permite_selecao="1" tem_inputs="1" tipo_inputs="radio" multiplo="0" selecionar_todos="0" filtro="1" classe_botao="btn-dark" classe_dropdown="dropdown-visao " class="div_combobox" placeholder="(Selecione)" name_inpus="_153182070" num_max_texto_botao="5" funcao_filtro="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                                                        <button type="button" class="btn dropdown-toggle btn-dark" data-bs-toggle="dropdown" aria-expanded="false" num_max_texto_botao="5" data-bs-auto-close="outside">Rca</button>
                                                                                                                        <ul class="dropdown-menu dropdown-visao" onclick="window.fnhtml.fndrop.clicou_dropdown(event,this)" permite_selecao="true">
                                                                                                                            <input type="text" class="input_filtro_dropdown rounded" placeholder="(filtro)" onkeyup="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                                                            <li opcoes_texto_opcao="Origem de Dados" opcoes_texto_botao="Origem de Dados" opcoes_valor_opcao="Origem de Dados" class="dropdown-item li" data-valor_opcao="Origem de Dados" data-texto_botao="Origem de Dados"><label textodepois="1"><input type="radio" name="_153182070">Origem de Dados</label></li>
                                                                                                                            <li opcoes_texto_opcao="Filial" opcoes_texto_botao="Filial" opcoes_valor_opcao="Filial" class="dropdown-item li" data-valor_opcao="Filial" data-texto_botao="Filial"><label textodepois="1"><input type="radio" name="_153182070">Filial</label></li>
                                                                                                                            <li opcoes_texto_opcao="Fornecedor" opcoes_texto_botao="Fornecedor" opcoes_valor_opcao="Fornecedor" class="dropdown-item li" data-valor_opcao="Fornecedor" data-texto_botao="Fornecedor"><label textodepois="1"><input type="radio" name="_153182070">Fornecedor</label></li>
                                                                                                                            <li opcoes_texto_opcao="Cidade" opcoes_texto_botao="Cidade" opcoes_valor_opcao="Cidade" class="dropdown-item li" data-valor_opcao="Cidade" data-texto_botao="Cidade"><label textodepois="1"><input type="radio" name="_153182070">Cidade</label></li>
                                                                                                                            <li opcoes_texto_opcao="Supervisor" opcoes_texto_botao="Supervisor" opcoes_valor_opcao="Supervisor" class="dropdown-item li" data-valor_opcao="Supervisor" data-texto_botao="Supervisor"><label textodepois="1"><input type="radio" name="_153182070">Supervisor</label></li>
                                                                                                                            <li opcoes_texto_opcao="Rca" opcoes_texto_botao="Rca" opcoes_valor_opcao="Rca" class="dropdown-item li" data-valor_opcao="Rca" data-texto_botao="Rca"><label textodepois="1"><input type="radio" name="_153182070" checked="1">Rca</label></li>
                                                                                                                            <li opcoes_texto_opcao="Ramo de Atividade" opcoes_texto_botao="Ramo de Atividade" opcoes_valor_opcao="Ramo de Atividade" class="dropdown-item li" data-valor_opcao="Ramo de Atividade" data-texto_botao="Ramo de Atividade"><label textodepois="1"><input type="radio" name="_153182070">Ramo de Atividade</label></li>
                                                                                                                            <li opcoes_texto_opcao="Departamento" opcoes_texto_botao="Departamento" opcoes_valor_opcao="Departamento" class="dropdown-item li" data-valor_opcao="Departamento" data-texto_botao="Departamento"><label textodepois="1"><input type="radio" name="_153182070">Departamento</label></li>
                                                                                                                            <li opcoes_texto_opcao="Produto" opcoes_texto_botao="Produto" opcoes_valor_opcao="Produto" class="dropdown-item li" data-valor_opcao="Produto" data-texto_botao="Produto"><label textodepois="1"><input type="radio" name="_153182070">Produto</label></li>
                                                                                                                            <li opcoes_texto_opcao="Cliente" opcoes_texto_botao="Cliente" opcoes_valor_opcao="Cliente" class="dropdown-item li" data-valor_opcao="Cliente" data-texto_botao="Cliente"><label textodepois="1"><input type="radio" name="_153182070">Cliente</label></li>
                                                                                                                            <li opcoes_texto_opcao="Rota" opcoes_texto_botao="Rota" opcoes_valor_opcao="Rota" class="dropdown-item li" data-valor_opcao="Rota" data-texto_botao="Rota"><label textodepois="1"><input type="radio" name="_153182070">Rota</label></li>
                                                                                                                            <li opcoes_texto_opcao="Praca" opcoes_texto_botao="Praca" opcoes_valor_opcao="Praca" class="dropdown-item li" data-valor_opcao="Praca" data-texto_botao="Praca"><label textodepois="1"><input type="radio" name="_153182070">Praca</label></li>
                                                                                                                            <li opcoes_texto_opcao="Negocio Aurora" opcoes_texto_botao="Negocio Aurora" opcoes_valor_opcao="Negocio Aurora" class="dropdown-item li" data-valor_opcao="Negocio Aurora" data-texto_botao="Negocio Aurora"><label textodepois="1"><input type="radio" name="_153182070">Negocio Aurora</label></li>
                                                                                                                            <li opcoes_texto_opcao="Categoria Aurora" opcoes_texto_botao="Categoria Aurora" opcoes_valor_opcao="Categoria Aurora" class="dropdown-item li" data-valor_opcao="Categoria Aurora" data-texto_botao="Categoria Aurora"><label textodepois="1"><input type="radio" name="_153182070">Categoria Aurora</label></li>
                                                                                                                            <li opcoes_texto_opcao="Rede de clientes" opcoes_texto_botao="Rede de clientes" opcoes_valor_opcao="Rede de clientes" class="dropdown-item li" data-valor_opcao="Rede de clientes" data-texto_botao="Rede de clientes"><label textodepois="1"><input type="radio" name="_153182070">Rede de clientes</label></li>
                                                                                                                        </ul>
                                                                                                                    </div>
                                                                                                                    </div>
                                                                                                                    <div class="col-auto">
                                                                                                                    <div tipo_inputs="radio" multiplo="nao" selecionar_todos="nao" filtro="nao" class="operacao div_combobox" tem_inputs="1" permite_selecao="1" placeholder="(Selecione)" classe_botao="btn-dark" name_inpus="_416381153" num_max_texto_botao="5" funcao_filtro="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                                                        <button type="button" class="btn dropdown-toggle btn-dark" data-bs-toggle="dropdown" aria-expanded="false" num_max_texto_botao="5" data-bs-auto-close="outside">Igual a</button>
                                                                                                                        <ul class="dropdown-menu" onclick="window.fnhtml.fndrop.clicou_dropdown(event,this)" permite_selecao="true">
                                                                                                                            <label class="label_selecionar_todos" textodepois="1"><input type="checkbox" class="input_selecionar_todos" onchange="window.fnhtml.fndrop.selecionou_todos_dropdown(event,this)">Selecionar Todos</label><input type="text" class="input_filtro_dropdown rounded" placeholder="(filtro)" onkeyup="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                                                            <li opcoes_texto_opcao="Igual a" opcoes_texto_botao="Igual a" opcoes_valor_opcao="Igual a" class="dropdown-item li" data-valor_opcao="Igual a" data-texto_botao="Igual a"><label textodepois="1"><input type="radio" name="_416381153" checked="1">Igual a</label></li>
                                                                                                                            <li opcoes_texto_opcao="Diferente de" opcoes_texto_botao="Diferente de" opcoes_valor_opcao="Diferente de" class="dropdown-item li" data-valor_opcao="Diferente de" data-texto_botao="Diferente de"><label textodepois="1"><input type="radio" name="_416381153">Diferente de</label></li>
                                                                                                                        </ul>
                                                                                                                    </div>
                                                                                                                    </div>
                                                                                                                    <div class="col-auto">
                                                                                                                    <div visao="Rca" permite_selecao="1" class="condicionante div_combobox" tipo_inputs="checkbox" selecionar_todos="1" multiplo="1" filtro="1" tem_inputs="1" placeholder="(Selecione)" classe_botao="btn-dark" num_max_texto_botao="5" funcao_filtro="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                                                        <button type="button" class="btn dropdown-toggle btn-dark" data-bs-toggle="dropdown" aria-expanded="false" num_max_texto_botao="5" data-bs-auto-close="outside">Todos (86)</button>
                                                                                                                        <ul class="dropdown-menu" onclick="window.fnhtml.fndrop.clicou_dropdown(event,this)" permite_selecao="true">
                                                                                                                            <label class="label_selecionar_todos" textodepois="1"><input type="checkbox" class="input_selecionar_todos" onchange="window.fnhtml.fndrop.selecionou_todos_dropdown(event,this)">Selecionar Todos</label><input type="text" class="input_filtro_dropdown rounded" placeholder="(filtro)" onkeyup="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                                                            <li opcoes_texto_opcao="1-CARLOS LEMOS " opcoes_valor_opcao="rca=1" opcoes_texto_botao="1" class="dropdown-item li" data-valor_opcao="rca=1" data-texto_botao="1"><label textodepois="1"><input type="checkbox" checked="1">1-CARLOS LEMOS</label></li>
                                                                                                                            <li opcoes_texto_opcao="101-ANTONIO FURLAN LARA" opcoes_valor_opcao="rca=101" opcoes_texto_botao="101" class="dropdown-item li" data-valor_opcao="rca=101" data-texto_botao="101"><label textodepois="1"><input type="checkbox" checked="1">101-ANTONIO FURLAN LARA</label></li>
                                                                                                                            <li opcoes_texto_opcao="102-ARAYAN LUIZ SCHIAVINI" opcoes_valor_opcao="rca=102" opcoes_texto_botao="102" class="dropdown-item li" data-valor_opcao="rca=102" data-texto_botao="102"><label textodepois="1"><input type="checkbox" checked="1">102-ARAYAN LUIZ SCHIAVINI</label></li>
                                                                                                                            <li opcoes_texto_opcao="103-AIRTON MARQUES DOS SANTOS " opcoes_valor_opcao="rca=103" opcoes_texto_botao="103" class="dropdown-item li" data-valor_opcao="rca=103" data-texto_botao="103"><label textodepois="1"><input type="checkbox" checked="1">103-AIRTON MARQUES DOS SANTOS</label></li>
                                                                                                                            <li opcoes_texto_opcao="104-EDSON ANGELO LOREZI" opcoes_valor_opcao="rca=104" opcoes_texto_botao="104" class="dropdown-item li" data-valor_opcao="rca=104" data-texto_botao="104"><label textodepois="1"><input type="checkbox" checked="1">104-EDSON ANGELO LOREZI</label></li>
                                                                                                                            <li opcoes_texto_opcao="105-DERCIO PEREIRA DA CUNHA" opcoes_valor_opcao="rca=105" opcoes_texto_botao="105" class="dropdown-item li" data-valor_opcao="rca=105" data-texto_botao="105"><label textodepois="1"><input type="checkbox" checked="1">105-DERCIO PEREIRA DA CUNHA</label></li>
                                                                                                                            <li opcoes_texto_opcao="106-ANTONIO LORENZETTI" opcoes_valor_opcao="rca=106" opcoes_texto_botao="106" class="dropdown-item li" data-valor_opcao="rca=106" data-texto_botao="106"><label textodepois="1"><input type="checkbox" checked="1">106-ANTONIO LORENZETTI</label></li>
                                                                                                                            <li opcoes_texto_opcao="107-LUIZ CARLOS DE MARCHI" opcoes_valor_opcao="rca=107" opcoes_texto_botao="107" class="dropdown-item li" data-valor_opcao="rca=107" data-texto_botao="107"><label textodepois="1"><input type="checkbox" checked="1">107-LUIZ CARLOS DE MARCHI</label></li>
                                                                                                                            <li opcoes_texto_opcao="108-ESMAEL MARCELO ULKOWSKI" opcoes_valor_opcao="rca=108" opcoes_texto_botao="108" class="dropdown-item li" data-valor_opcao="rca=108" data-texto_botao="108"><label textodepois="1"><input type="checkbox" checked="1">108-ESMAEL MARCELO ULKOWSKI</label></li>
                                                                                                                            <li opcoes_texto_opcao="109-ROGERIO MAZZO" opcoes_valor_opcao="rca=109" opcoes_texto_botao="109" class="dropdown-item li" data-valor_opcao="rca=109" data-texto_botao="109"><label textodepois="1"><input type="checkbox" checked="1">109-ROGERIO MAZZO</label></li>
                                                                                                                            <li opcoes_texto_opcao="110-CLEITON JOSE ESSER" opcoes_valor_opcao="rca=110" opcoes_texto_botao="110" class="dropdown-item li" data-valor_opcao="rca=110" data-texto_botao="110"><label textodepois="1"><input type="checkbox" checked="1">110-CLEITON JOSE ESSER</label></li>
                                                                                                                            <li opcoes_texto_opcao="111-HAMILTON APARECIDO SILVEIRA" opcoes_valor_opcao="rca=111" opcoes_texto_botao="111" class="dropdown-item li" data-valor_opcao="rca=111" data-texto_botao="111"><label textodepois="1"><input type="checkbox" checked="1">111-HAMILTON APARECIDO SILVEIRA</label></li>
                                                                                                                            <li opcoes_texto_opcao="112-INACIO SCHLICKMANN" opcoes_valor_opcao="rca=112" opcoes_texto_botao="112" class="dropdown-item li" data-valor_opcao="rca=112" data-texto_botao="112"><label textodepois="1"><input type="checkbox" checked="1">112-INACIO SCHLICKMANN</label></li>
                                                                                                                            <li opcoes_texto_opcao="113-ADRIANO GARCIA MARIN" opcoes_valor_opcao="rca=113" opcoes_texto_botao="113" class="dropdown-item li" data-valor_opcao="rca=113" data-texto_botao="113"><label textodepois="1"><input type="checkbox" checked="1">113-ADRIANO GARCIA MARIN</label></li>
                                                                                                                            <li opcoes_texto_opcao="114-ARAYAN SCHIAVINI" opcoes_valor_opcao="rca=114" opcoes_texto_botao="114" class="dropdown-item li" data-valor_opcao="rca=114" data-texto_botao="114"><label textodepois="1"><input type="checkbox" checked="1">114-ARAYAN SCHIAVINI</label></li>
                                                                                                                            <li opcoes_texto_opcao="115-PATRICIA LOPES" opcoes_valor_opcao="rca=115" opcoes_texto_botao="115" class="dropdown-item li" data-valor_opcao="rca=115" data-texto_botao="115"><label textodepois="1"><input type="checkbox" checked="1">115-PATRICIA LOPES</label></li>
                                                                                                                            <li opcoes_texto_opcao="116-RUDSON NOE PEREIRA DE LIMA" opcoes_valor_opcao="rca=116" opcoes_texto_botao="116" class="dropdown-item li" data-valor_opcao="rca=116" data-texto_botao="116"><label textodepois="1"><input type="checkbox" checked="1">116-RUDSON NOE PEREIRA DE LIMA</label></li>
                                                                                                                            <li opcoes_texto_opcao="117-EDSON NUNES" opcoes_valor_opcao="rca=117" opcoes_texto_botao="117" class="dropdown-item li" data-valor_opcao="rca=117" data-texto_botao="117"><label textodepois="1"><input type="checkbox" checked="1">117-EDSON NUNES</label></li>
                                                                                                                            <li opcoes_texto_opcao="118-ANDERSON" opcoes_valor_opcao="rca=118" opcoes_texto_botao="118" class="dropdown-item li" data-valor_opcao="rca=118" data-texto_botao="118"><label textodepois="1"><input type="checkbox" checked="1">118-ANDERSON</label></li>
                                                                                                                            <li opcoes_texto_opcao="121-VILMAR ALVES PINTO" opcoes_valor_opcao="rca=121" opcoes_texto_botao="121" class="dropdown-item li" data-valor_opcao="rca=121" data-texto_botao="121"><label textodepois="1"><input type="checkbox" checked="1">121-VILMAR ALVES PINTO</label></li>
                                                                                                                            <li opcoes_texto_opcao="122-VILMA ROCHA" opcoes_valor_opcao="rca=122" opcoes_texto_botao="122" class="dropdown-item li" data-valor_opcao="rca=122" data-texto_botao="122"><label textodepois="1"><input type="checkbox" checked="1">122-VILMA ROCHA</label></li>
                                                                                                                            <li opcoes_texto_opcao="123-ALEXSANDRO FURQUIM" opcoes_valor_opcao="rca=123" opcoes_texto_botao="123" class="dropdown-item li" data-valor_opcao="rca=123" data-texto_botao="123"><label textodepois="1"><input type="checkbox" checked="1">123-ALEXSANDRO FURQUIM</label></li>
                                                                                                                            <li opcoes_texto_opcao="124-EVANDRO LUIZ PROCHOSKI" opcoes_valor_opcao="rca=124" opcoes_texto_botao="124" class="dropdown-item li" data-valor_opcao="rca=124" data-texto_botao="124"><label textodepois="1"><input type="checkbox" checked="1">124-EVANDRO LUIZ PROCHOSKI</label></li>
                                                                                                                            <li opcoes_texto_opcao="126-JOSE ADRIANO DE FREITAS" opcoes_valor_opcao="rca=126" opcoes_texto_botao="126" class="dropdown-item li" data-valor_opcao="rca=126" data-texto_botao="126"><label textodepois="1"><input type="checkbox" checked="1">126-JOSE ADRIANO DE FREITAS</label></li>
                                                                                                                            <li opcoes_texto_opcao="127-MARCIO ROBERTO" opcoes_valor_opcao="rca=127" opcoes_texto_botao="127" class="dropdown-item li" data-valor_opcao="rca=127" data-texto_botao="127"><label textodepois="1"><input type="checkbox" checked="1">127-MARCIO ROBERTO</label></li>
                                                                                                                            <li opcoes_texto_opcao="128-JOSE UBIRAJARA MENON" opcoes_valor_opcao="rca=128" opcoes_texto_botao="128" class="dropdown-item li" data-valor_opcao="rca=128" data-texto_botao="128"><label textodepois="1"><input type="checkbox" checked="1">128-JOSE UBIRAJARA MENON</label></li>
                                                                                                                            <li opcoes_texto_opcao="129-GIOVANNI LARA" opcoes_valor_opcao="rca=129" opcoes_texto_botao="129" class="dropdown-item li" data-valor_opcao="rca=129" data-texto_botao="129"><label textodepois="1"><input type="checkbox" checked="1">129-GIOVANNI LARA</label></li>
                                                                                                                            <li opcoes_texto_opcao="130-LUIZ C SCHIAVINI" opcoes_valor_opcao="rca=130" opcoes_texto_botao="130" class="dropdown-item li" data-valor_opcao="rca=130" data-texto_botao="130"><label textodepois="1"><input type="checkbox" checked="1">130-LUIZ C SCHIAVINI</label></li>
                                                                                                                            <li opcoes_texto_opcao="140-JACKELINE" opcoes_valor_opcao="rca=140" opcoes_texto_botao="140" class="dropdown-item li" data-valor_opcao="rca=140" data-texto_botao="140"><label textodepois="1"><input type="checkbox" checked="1">140-JACKELINE</label></li>
                                                                                                                            <li opcoes_texto_opcao="150-CLIENTES INATIVADOS" opcoes_valor_opcao="rca=150" opcoes_texto_botao="150" class="dropdown-item li" data-valor_opcao="rca=150" data-texto_botao="150"><label textodepois="1"><input type="checkbox" checked="1">150-CLIENTES INATIVADOS</label></li>
                                                                                                                            <li opcoes_texto_opcao="180-ECOMERCE" opcoes_valor_opcao="rca=180" opcoes_texto_botao="180" class="dropdown-item li" data-valor_opcao="rca=180" data-texto_botao="180"><label textodepois="1"><input type="checkbox" checked="1">180-ECOMERCE</label></li>
                                                                                                                            <li opcoes_texto_opcao="2-REGINALDO CASTELANI" opcoes_valor_opcao="rca=2" opcoes_texto_botao="2" class="dropdown-item li" data-valor_opcao="rca=2" data-texto_botao="2"><label textodepois="1"><input type="checkbox" checked="1">2-REGINALDO CASTELANI</label></li>
                                                                                                                            <li opcoes_texto_opcao="201-PATRICIA MAYRA MELO LOPES" opcoes_valor_opcao="rca=201" opcoes_texto_botao="201" class="dropdown-item li" data-valor_opcao="rca=201" data-texto_botao="201"><label textodepois="1"><input type="checkbox" checked="1">201-PATRICIA MAYRA MELO LOPES</label></li>
                                                                                                                            <li opcoes_texto_opcao="202-VICENTE MORENO JUNIOR" opcoes_valor_opcao="rca=202" opcoes_texto_botao="202" class="dropdown-item li" data-valor_opcao="rca=202" data-texto_botao="202"><label textodepois="1"><input type="checkbox" checked="1">202-VICENTE MORENO JUNIOR</label></li>
                                                                                                                            <li opcoes_texto_opcao="203-KEBIS MARCAL" opcoes_valor_opcao="rca=203" opcoes_texto_botao="203" class="dropdown-item li" data-valor_opcao="rca=203" data-texto_botao="203"><label textodepois="1"><input type="checkbox" checked="1">203-KEBIS MARCAL</label></li>
                                                                                                                            <li opcoes_texto_opcao="204-MARCIO DE CAMILLO" opcoes_valor_opcao="rca=204" opcoes_texto_botao="204" class="dropdown-item li" data-valor_opcao="rca=204" data-texto_botao="204"><label textodepois="1"><input type="checkbox" checked="1">204-MARCIO DE CAMILLO</label></li>
                                                                                                                            <li opcoes_texto_opcao="205-ALAN PIERRE GARCIA" opcoes_valor_opcao="rca=205" opcoes_texto_botao="205" class="dropdown-item li" data-valor_opcao="rca=205" data-texto_botao="205"><label textodepois="1"><input type="checkbox" checked="1">205-ALAN PIERRE GARCIA</label></li>
                                                                                                                            <li opcoes_texto_opcao="206-EDVALDO BISPO PACHECO" opcoes_valor_opcao="rca=206" opcoes_texto_botao="206" class="dropdown-item li" data-valor_opcao="rca=206" data-texto_botao="206"><label textodepois="1"><input type="checkbox" checked="1">206-EDVALDO BISPO PACHECO</label></li>
                                                                                                                            <li opcoes_texto_opcao="207-HUDSON FERNANDO ALBANEZ BARBOSA " opcoes_valor_opcao="rca=207" opcoes_texto_botao="207" class="dropdown-item li" data-valor_opcao="rca=207" data-texto_botao="207"><label textodepois="1"><input type="checkbox" checked="1">207-HUDSON FERNANDO ALBANEZ BARBOSA</label></li>
                                                                                                                            <li opcoes_texto_opcao="208-ANDERSON ANDREI GERALDO" opcoes_valor_opcao="rca=208" opcoes_texto_botao="208" class="dropdown-item li" data-valor_opcao="rca=208" data-texto_botao="208"><label textodepois="1"><input type="checkbox" checked="1">208-ANDERSON ANDREI GERALDO</label></li>
                                                                                                                            <li opcoes_texto_opcao="209-AGOSTINHO RODRIGUES PEREIRA" opcoes_valor_opcao="rca=209" opcoes_texto_botao="209" class="dropdown-item li" data-valor_opcao="rca=209" data-texto_botao="209"><label textodepois="1"><input type="checkbox" checked="1">209-AGOSTINHO RODRIGUES PEREIRA</label></li>
                                                                                                                            <li opcoes_texto_opcao="210-JEVERSON DA ZILVA" opcoes_valor_opcao="rca=210" opcoes_texto_botao="210" class="dropdown-item li" data-valor_opcao="rca=210" data-texto_botao="210"><label textodepois="1"><input type="checkbox" checked="1">210-JEVERSON DA ZILVA</label></li>
                                                                                                                            <li opcoes_texto_opcao="211-RICARDO ALMEIDA MOREIRA" opcoes_valor_opcao="rca=211" opcoes_texto_botao="211" class="dropdown-item li" data-valor_opcao="rca=211" data-texto_botao="211"><label textodepois="1"><input type="checkbox" checked="1">211-RICARDO ALMEIDA MOREIRA</label></li>
                                                                                                                            <li opcoes_texto_opcao="212-CARLOS ANTONIO AGUIAR" opcoes_valor_opcao="rca=212" opcoes_texto_botao="212" class="dropdown-item li" data-valor_opcao="rca=212" data-texto_botao="212"><label textodepois="1"><input type="checkbox" checked="1">212-CARLOS ANTONIO AGUIAR</label></li>
                                                                                                                            <li opcoes_texto_opcao="213-LUIZ ALBANO GENARO" opcoes_valor_opcao="rca=213" opcoes_texto_botao="213" class="dropdown-item li" data-valor_opcao="rca=213" data-texto_botao="213"><label textodepois="1"><input type="checkbox" checked="1">213-LUIZ ALBANO GENARO</label></li>
                                                                                                                            <li opcoes_texto_opcao="214-CRISTIAN FREITAS " opcoes_valor_opcao="rca=214" opcoes_texto_botao="214" class="dropdown-item li" data-valor_opcao="rca=214" data-texto_botao="214"><label textodepois="1"><input type="checkbox" checked="1">214-CRISTIAN FREITAS</label></li>
                                                                                                                            <li opcoes_texto_opcao="215-THIAGO OLIVEIRA DIAS" opcoes_valor_opcao="rca=215" opcoes_texto_botao="215" class="dropdown-item li" data-valor_opcao="rca=215" data-texto_botao="215"><label textodepois="1"><input type="checkbox" checked="1">215-THIAGO OLIVEIRA DIAS</label></li>
                                                                                                                            <li opcoes_texto_opcao="216-REINALDO PAULINO MENDES" opcoes_valor_opcao="rca=216" opcoes_texto_botao="216" class="dropdown-item li" data-valor_opcao="rca=216" data-texto_botao="216"><label textodepois="1"><input type="checkbox" checked="1">216-REINALDO PAULINO MENDES</label></li>
                                                                                                                            <li opcoes_texto_opcao="217-TIAGO MENEGHETTE DE MATOS" opcoes_valor_opcao="rca=217" opcoes_texto_botao="217" class="dropdown-item li" data-valor_opcao="rca=217" data-texto_botao="217"><label textodepois="1"><input type="checkbox" checked="1">217-TIAGO MENEGHETTE DE MATOS</label></li>
                                                                                                                            <li opcoes_texto_opcao="218-ROBSON PAULO PALHARES" opcoes_valor_opcao="rca=218" opcoes_texto_botao="218" class="dropdown-item li" data-valor_opcao="rca=218" data-texto_botao="218"><label textodepois="1"><input type="checkbox" checked="1">218-ROBSON PAULO PALHARES</label></li>
                                                                                                                            <li opcoes_texto_opcao="219-PEDRO AUGUSTO SOARES DE ARAUJO LOURENCO" opcoes_valor_opcao="rca=219" opcoes_texto_botao="219" class="dropdown-item li" data-valor_opcao="rca=219" data-texto_botao="219"><label textodepois="1"><input type="checkbox" checked="1">219-PEDRO AUGUSTO SOARES DE ARAUJO LOURENCO</label></li>
                                                                                                                            <li opcoes_texto_opcao="220-FABIO JILENO ROSSATI" opcoes_valor_opcao="rca=220" opcoes_texto_botao="220" class="dropdown-item li" data-valor_opcao="rca=220" data-texto_botao="220"><label textodepois="1"><input type="checkbox" checked="1">220-FABIO JILENO ROSSATI</label></li>
                                                                                                                            <li opcoes_texto_opcao="221-NAZIH DIAB AL GHADBAN" opcoes_valor_opcao="rca=221" opcoes_texto_botao="221" class="dropdown-item li" data-valor_opcao="rca=221" data-texto_botao="221"><label textodepois="1"><input type="checkbox" checked="1">221-NAZIH DIAB AL GHADBAN</label></li>
                                                                                                                            <li opcoes_texto_opcao="222-JUMBO-LONDRINA" opcoes_valor_opcao="rca=222" opcoes_texto_botao="222" class="dropdown-item li" data-valor_opcao="rca=222" data-texto_botao="222"><label textodepois="1"><input type="checkbox" checked="1">222-JUMBO-LONDRINA</label></li>
                                                                                                                            <li opcoes_texto_opcao="223-LUCIANO JOSE DA SILVA " opcoes_valor_opcao="rca=223" opcoes_texto_botao="223" class="dropdown-item li" data-valor_opcao="rca=223" data-texto_botao="223"><label textodepois="1"><input type="checkbox" checked="1">223-LUCIANO JOSE DA SILVA</label></li>
                                                                                                                            <li opcoes_texto_opcao="224-ADILSON APARECIDO LAZARINI" opcoes_valor_opcao="rca=224" opcoes_texto_botao="224" class="dropdown-item li" data-valor_opcao="rca=224" data-texto_botao="224"><label textodepois="1"><input type="checkbox" checked="1">224-ADILSON APARECIDO LAZARINI</label></li>
                                                                                                                            <li opcoes_texto_opcao="225-CASSIANA ROUBLES DOS SANTOS" opcoes_valor_opcao="rca=225" opcoes_texto_botao="225" class="dropdown-item li" data-valor_opcao="rca=225" data-texto_botao="225"><label textodepois="1"><input type="checkbox" checked="1">225-CASSIANA ROUBLES DOS SANTOS</label></li>
                                                                                                                            <li opcoes_texto_opcao="226-GENTIL PINHEIRO JUNIOR" opcoes_valor_opcao="rca=226" opcoes_texto_botao="226" class="dropdown-item li" data-valor_opcao="rca=226" data-texto_botao="226"><label textodepois="1"><input type="checkbox" checked="1">226-GENTIL PINHEIRO JUNIOR</label></li>
                                                                                                                            <li opcoes_texto_opcao="227-PAULO SERGIO GONCALVES" opcoes_valor_opcao="rca=227" opcoes_texto_botao="227" class="dropdown-item li" data-valor_opcao="rca=227" data-texto_botao="227"><label textodepois="1"><input type="checkbox" checked="1">227-PAULO SERGIO GONCALVES</label></li>
                                                                                                                            <li opcoes_texto_opcao="228-MAYCON - RESERVA" opcoes_valor_opcao="rca=228" opcoes_texto_botao="228" class="dropdown-item li" data-valor_opcao="rca=228" data-texto_botao="228"><label textodepois="1"><input type="checkbox" checked="1">228-MAYCON - RESERVA</label></li>
                                                                                                                            <li opcoes_texto_opcao="229-CARLOS ROBERTO DE SOUZA MORAES" opcoes_valor_opcao="rca=229" opcoes_texto_botao="229" class="dropdown-item li" data-valor_opcao="rca=229" data-texto_botao="229"><label textodepois="1"><input type="checkbox" checked="1">229-CARLOS ROBERTO DE SOUZA MORAES</label></li>
                                                                                                                            <li opcoes_texto_opcao="230-BALCAO" opcoes_valor_opcao="rca=230" opcoes_texto_botao="230" class="dropdown-item li" data-valor_opcao="rca=230" data-texto_botao="230"><label textodepois="1"><input type="checkbox" checked="1">230-BALCAO</label></li>
                                                                                                                            <li opcoes_texto_opcao="231-EDINHO" opcoes_valor_opcao="rca=231" opcoes_texto_botao="231" class="dropdown-item li" data-valor_opcao="rca=231" data-texto_botao="231"><label textodepois="1"><input type="checkbox" checked="1">231-EDINHO</label></li>
                                                                                                                            <li opcoes_texto_opcao="232-WELLINGTON FRANCISCO SIQUEIRA" opcoes_valor_opcao="rca=232" opcoes_texto_botao="232" class="dropdown-item li" data-valor_opcao="rca=232" data-texto_botao="232"><label textodepois="1"><input type="checkbox" checked="1">232-WELLINGTON FRANCISCO SIQUEIRA</label></li>
                                                                                                                            <li opcoes_texto_opcao="234-BRUNA ANDRESSA POLETTI" opcoes_valor_opcao="rca=234" opcoes_texto_botao="234" class="dropdown-item li" data-valor_opcao="rca=234" data-texto_botao="234"><label textodepois="1"><input type="checkbox" checked="1">234-BRUNA ANDRESSA POLETTI</label></li>
                                                                                                                            <li opcoes_texto_opcao="236-ALEXANDRE FERREIRA FIM" opcoes_valor_opcao="rca=236" opcoes_texto_botao="236" class="dropdown-item li" data-valor_opcao="rca=236" data-texto_botao="236"><label textodepois="1"><input type="checkbox" checked="1">236-ALEXANDRE FERREIRA FIM</label></li>
                                                                                                                            <li opcoes_texto_opcao="237-LUCIANO DOS SANTOS " opcoes_valor_opcao="rca=237" opcoes_texto_botao="237" class="dropdown-item li" data-valor_opcao="rca=237" data-texto_botao="237"><label textodepois="1"><input type="checkbox" checked="1">237-LUCIANO DOS SANTOS</label></li>
                                                                                                                            <li opcoes_texto_opcao="240-JACKELINE" opcoes_valor_opcao="rca=240" opcoes_texto_botao="240" class="dropdown-item li" data-valor_opcao="rca=240" data-texto_botao="240"><label textodepois="1"><input type="checkbox" checked="1">240-JACKELINE</label></li>
                                                                                                                            <li opcoes_texto_opcao="250-ALTAIR SOTANA" opcoes_valor_opcao="rca=250" opcoes_texto_botao="250" class="dropdown-item li" data-valor_opcao="rca=250" data-texto_botao="250"><label textodepois="1"><input type="checkbox" checked="1">250-ALTAIR SOTANA</label></li>
                                                                                                                            <li opcoes_texto_opcao="251-INATIVOS - BAIXADOS" opcoes_valor_opcao="rca=251" opcoes_texto_botao="251" class="dropdown-item li" data-valor_opcao="rca=251" data-texto_botao="251"><label textodepois="1"><input type="checkbox" checked="1">251-INATIVOS - BAIXADOS</label></li>
                                                                                                                            <li opcoes_texto_opcao="3-CRISTIAN  FREITAS DE LIMA FERNANDES" opcoes_valor_opcao="rca=3" opcoes_texto_botao="3" class="dropdown-item li" data-valor_opcao="rca=3" data-texto_botao="3"><label textodepois="1"><input type="checkbox" checked="1">3-CRISTIAN  FREITAS DE LIMA FERNANDES</label></li>
                                                                                                                            <li opcoes_texto_opcao="301-EDSON NUNES" opcoes_valor_opcao="rca=301" opcoes_texto_botao="301" class="dropdown-item li" data-valor_opcao="rca=301" data-texto_botao="301"><label textodepois="1"><input type="checkbox" checked="1">301-EDSON NUNES</label></li>
                                                                                                                            <li opcoes_texto_opcao="302-LUIZ SCHIAVINI MS" opcoes_valor_opcao="rca=302" opcoes_texto_botao="302" class="dropdown-item li" data-valor_opcao="rca=302" data-texto_botao="302"><label textodepois="1"><input type="checkbox" checked="1">302-LUIZ SCHIAVINI MS</label></li>
                                                                                                                            <li opcoes_texto_opcao="303-CARLOS LEMOS MS" opcoes_valor_opcao="rca=303" opcoes_texto_botao="303" class="dropdown-item li" data-valor_opcao="rca=303" data-texto_botao="303"><label textodepois="1"><input type="checkbox" checked="1">303-CARLOS LEMOS MS</label></li>
                                                                                                                            <li opcoes_texto_opcao="304-JOAO VIEIRA DO PRADO" opcoes_valor_opcao="rca=304" opcoes_texto_botao="304" class="dropdown-item li" data-valor_opcao="rca=304" data-texto_botao="304"><label textodepois="1"><input type="checkbox" checked="1">304-JOAO VIEIRA DO PRADO</label></li>
                                                                                                                            <li opcoes_texto_opcao="305-ADILSON DE LIMA AMERICANO" opcoes_valor_opcao="rca=305" opcoes_texto_botao="305" class="dropdown-item li" data-valor_opcao="rca=305" data-texto_botao="305"><label textodepois="1"><input type="checkbox" checked="1">305-ADILSON DE LIMA AMERICANO</label></li>
                                                                                                                            <li opcoes_texto_opcao="306-ARISTEU PADILHA DO AMARAL" opcoes_valor_opcao="rca=306" opcoes_texto_botao="306" class="dropdown-item li" data-valor_opcao="rca=306" data-texto_botao="306"><label textodepois="1"><input type="checkbox" checked="1">306-ARISTEU PADILHA DO AMARAL</label></li>
                                                                                                                            <li opcoes_texto_opcao="307-LUCIANO PEREIRA" opcoes_valor_opcao="rca=307" opcoes_texto_botao="307" class="dropdown-item li" data-valor_opcao="rca=307" data-texto_botao="307"><label textodepois="1"><input type="checkbox" checked="1">307-LUCIANO PEREIRA</label></li>
                                                                                                                            <li opcoes_texto_opcao="308-ABRAO CARLOS PEIXOTO" opcoes_valor_opcao="rca=308" opcoes_texto_botao="308" class="dropdown-item li" data-valor_opcao="rca=308" data-texto_botao="308"><label textodepois="1"><input type="checkbox" checked="1">308-ABRAO CARLOS PEIXOTO</label></li>
                                                                                                                            <li opcoes_texto_opcao="309-GILBERTO DA SILVA" opcoes_valor_opcao="rca=309" opcoes_texto_botao="309" class="dropdown-item li" data-valor_opcao="rca=309" data-texto_botao="309"><label textodepois="1"><input type="checkbox" checked="1">309-GILBERTO DA SILVA</label></li>
                                                                                                                            <li opcoes_texto_opcao="310-DARBEM FILHO REP. COMERCIAIS" opcoes_valor_opcao="rca=310" opcoes_texto_botao="310" class="dropdown-item li" data-valor_opcao="rca=310" data-texto_botao="310"><label textodepois="1"><input type="checkbox" checked="1">310-DARBEM FILHO REP. COMERCIAIS</label></li>
                                                                                                                            <li opcoes_texto_opcao="311-REGINALDO RAMOS" opcoes_valor_opcao="rca=311" opcoes_texto_botao="311" class="dropdown-item li" data-valor_opcao="rca=311" data-texto_botao="311"><label textodepois="1"><input type="checkbox" checked="1">311-REGINALDO RAMOS</label></li>
                                                                                                                            <li opcoes_texto_opcao="312-DIOGO DE MEDEIROS FIGUEREDO LTDA" opcoes_valor_opcao="rca=312" opcoes_texto_botao="312" class="dropdown-item li" data-valor_opcao="rca=312" data-texto_botao="312"><label textodepois="1"><input type="checkbox" checked="1">312-DIOGO DE MEDEIROS FIGUEREDO LTDA</label></li>
                                                                                                                            <li opcoes_texto_opcao="333-JUMBO-CASCAVEL" opcoes_valor_opcao="rca=333" opcoes_texto_botao="333" class="dropdown-item li" data-valor_opcao="rca=333" data-texto_botao="333"><label textodepois="1"><input type="checkbox" checked="1">333-JUMBO-CASCAVEL</label></li>
                                                                                                                            <li opcoes_texto_opcao="4-PIRES" opcoes_valor_opcao="rca=4" opcoes_texto_botao="4" class="dropdown-item li" data-valor_opcao="rca=4" data-texto_botao="4"><label textodepois="1"><input type="checkbox" checked="1">4-PIRES</label></li>
                                                                                                                            <li opcoes_texto_opcao="6-LUIZ SCHIAVINI" opcoes_valor_opcao="rca=6" opcoes_texto_botao="6" class="dropdown-item li" data-valor_opcao="rca=6" data-texto_botao="6"><label textodepois="1"><input type="checkbox" checked="1">6-LUIZ SCHIAVINI</label></li>
                                                                                                                        </ul>
                                                                                                                    </div>
                                                                                                                    </div>
                                                                                                                </div>
                                                                                                            </div>
                                                                                                        </div>
                                                                                                        </div>
                                                                                                        <div class="div_opcao_controles_btns_img col-md-auto w-auto"></div>
                                                                                                    </div>
                                                                                                </div>
                                                                                            </div>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="div_botao_pesquisar d-grid gap-2 col-6 mx-auto mt-3"><button class="botao_pesquisar btn btn-primary" value="Pesquisar" data-visao="gestao_acessos" onclick="window.fnsisjd.pesquisar_dados(this)">Pesquisar</button></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="div_resultado_l2 row">
                                    <div class="div_resultado col"></div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
         </div>
      </div>
   </main>
</body>
<script type="module">
    import { fndt } from "/sjd/javascript/modulos/classes/data/FuncoesData.js";
    $("input.componente_data").eq(0).val(fndt.dataUSA(fndt.data_primeirodiames()));
    $("input.componente_data").eq(1).val(fndt.dataUSA(fndt.hoje()));
    $("input.inputano").val(fndt.dataBR_getAno(fndt.data_primeirodiames()));
</script>
</html>