<?php
    namespace SJD\logistica\relatorios_logistica;

    include_once($_SERVER['DOCUMENT_ROOT']."/SJD/php/initial_loads.php");

?>
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SisJD - Relatorio Entregas</title>
    <link href="/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link href="/sjd/css//1.1/estilos.css" rel="stylesheet">
    <script type="text/javascript" src="/sjd/javascript/polyfill.js"></script>
    <script type="text/javascript" src="/jquery/3.6.0/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <script type="module" src="/sjd/javascript/modulos/ModuloPrincipal.js?2.00"></script>
</head>
<body>
   <main style="display: block;">
      <div class="container-fluid p-0 m-0">
         <div class="row p-0 m-0">
             <div class="col p-0 m-0">
                <div id="barra_superior" class="barra_superior bg-dark text-white text-center text-uppercase fw-bolder position-relative">                              
                    <text class="position-absolute top-50 start-50 translate-middle">
                        Relatorio Entregas
                    </text>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div name="div_pagina" class="div_pagina container-fluid" style="width: 100%; min-width: 100%; inset: 50px 0px 0px;">
                    <div name="div_grid_linha_corpo_pagina" class="row">
                        <div name="div_grid_col_corpo_pagina" class="col">
                            <div name="div_conteudo_pagina" class="div_conteudo_pagina container-fluid _0_8655979748864595 _0_918544958606079">
                                <div></div>
                                <div name="div_entregas" class="div_entregas container-fluid corpo-conteudo" ajuda_elemento="Escolha uma ou mais visoes, um ou mais periodos, condicionantes, tipos de valores para ver seu relatorio personalizado!" data-tit_aba="Relatorio Entregas" data-nome="aba_rel_person">
                                <div class="div_opcoes_pesquisa_l1 row" titulo="Opcoes de Pesquisa" height="25px">
                                    <div class="div_opcoes_pesquisa m-1 col">
                                        <div class="accordion">
                                            <div titulo="Opcoes de Pesquisa" target="#painel_div_opcoes_pesquisa_corpo" class="accordion-item" aberto="1">
                                            <div class="accordion-header" titulo="Opcoes de Pesquisa" target="#painel_div_opcoes_pesquisa_corpo" aberto="1">
                                                <div data-bs-toggle="collapse" data-bs-target="#painel_div_opcoes_pesquisa_corpo" aberto="1" class="accordion-button" type="button" aria-expanded="true" aria-controls="painel_div_opcoes_pesquisa_corpo">Opcoes de Pesquisa</div>
                                            </div>
                                            <div id="painel_div_opcoes_pesquisa_corpo" class="collapse show">
                                                <div class="accordion-body" aberto="1">
                                                    <div class="div_opcoes_pesquisa_simples row">
                                                        <div class="div_opcoes_pesquisa_simples_col col">
                                                        <div class="accordion">
                                                            <div class="div_visoes accordion-item" titulo="Filtros" tipo="filtro" target="#visoes" aberto="1">
                                                                <div class="accordion-header" titulo="Filtros" target="#visoes" aberto="1">
                                                                    <div data-bs-toggle="collapse" data-bs-target="#visoes" aberto="1" class="accordion-button" type="button" aria-expanded="true" aria-controls="visoes">Filtros</div>
                                                                </div>
                                                                <div id="visoes" class="collapse show">
                                                                    <div class="accordion-body" aberto="1">
                                                                    <div class="row">
                                                                        <div class="col-auto mt-2 div_visao col">
                                                                            <div funcao_inclusao="window.fnsisjd.inserir_visao_pesquisa({elemento:this})" funcao_exclusao="window.fnsisjd.deletar_controles({elemento:this})" class="card">
                                                                                <div class="card-header">Carregamento</div>
                                                                                <div class="card-body">
                                                                                <div class="row">
                                                                                    <div class="col"><input type="number;input" label="Carregamento" placeholder="(Carregamento)" filtro="carregamento"></div>
                                                                                    <div class="div_opcao_controles_btns_img col-md-auto w-auto"></div>
                                                                                </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-auto mt-2 div_visao col">
                                                                            <div funcao_inclusao="window.fnsisjd.inserir_visao_pesquisa({elemento:this})" funcao_exclusao="window.fnsisjd.deletar_controles({elemento:this})" class="card">
                                                                                <div class="card-header">Motorista</div>
                                                                                <div class="card-body">
                                                                                <div class="row">
                                                                                    <div class="col">
                                                                                        <div label="Motorista" visao="Motorista" class="condicionante div_combobox" tipo_inputs="checkbox" selecionar_todos="1" multiplo="1" filtro="1" tem_inputs="1" placeholder="(Selecione)" classe_botao="btn-dark" num_max_texto_botao="5" funcao_filtro="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                            <button type="button" class="btn dropdown-toggle btn-dark" data-bs-toggle="dropdown" aria-expanded="false" num_max_texto_botao="5" data-bs-auto-close="outside">Todos (109)</button>
                                                                                            <ul class="dropdown-menu" onclick="window.fnhtml.fndrop.clicou_dropdown(event,this)">
                                                                                            <label class="label_selecionar_todos" textodepois="1"><input type="checkbox" class="input_selecionar_todos" onchange="window.fnhtml.fndrop.selecionou_todos_dropdown(event,this)">Selecionar Todos</label><input type="text" class="input_filtro_dropdown rounded" placeholder="(filtro)" onkeyup="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                            <li opcoes_texto_opcao="101-ADEMIR DA SILVA FERREIRA" opcoes_valor_opcao="motorista=101" opcoes_texto_botao="101" class="dropdown-item li" data-valor_opcao="motorista=101" data-texto_botao="101"><label textodepois="1"><input type="checkbox" checked="1">101-ADEMIR DA SILVA FERREIRA</label></li>
                                                                                            <li opcoes_texto_opcao="103-CARLOS FABRICIO DE SOUZA" opcoes_valor_opcao="motorista=103" opcoes_texto_botao="103" class="dropdown-item li" data-valor_opcao="motorista=103" data-texto_botao="103"><label textodepois="1"><input type="checkbox" checked="1">103-CARLOS FABRICIO DE SOUZA</label></li>
                                                                                            <li opcoes_texto_opcao="104-CARLOS FERREIRA DOS REIS" opcoes_valor_opcao="motorista=104" opcoes_texto_botao="104" class="dropdown-item li" data-valor_opcao="motorista=104" data-texto_botao="104"><label textodepois="1"><input type="checkbox" checked="1">104-CARLOS FERREIRA DOS REIS</label></li>
                                                                                            <li opcoes_texto_opcao="105-CLAYTON LOPES DA SILVA" opcoes_valor_opcao="motorista=105" opcoes_texto_botao="105" class="dropdown-item li" data-valor_opcao="motorista=105" data-texto_botao="105"><label textodepois="1"><input type="checkbox" checked="1">105-CLAYTON LOPES DA SILVA</label></li>
                                                                                            <li opcoes_texto_opcao="106-DIEGO APARECIDO DE CASTRO" opcoes_valor_opcao="motorista=106" opcoes_texto_botao="106" class="dropdown-item li" data-valor_opcao="motorista=106" data-texto_botao="106"><label textodepois="1"><input type="checkbox" checked="1">106-DIEGO APARECIDO DE CASTRO</label></li>
                                                                                            <li opcoes_texto_opcao="107-EMILIO ALVES PINTO" opcoes_valor_opcao="motorista=107" opcoes_texto_botao="107" class="dropdown-item li" data-valor_opcao="motorista=107" data-texto_botao="107"><label textodepois="1"><input type="checkbox" checked="1">107-EMILIO ALVES PINTO</label></li>
                                                                                            <li opcoes_texto_opcao="108-EZEQUIAS PIRES DA SILVA" opcoes_valor_opcao="motorista=108" opcoes_texto_botao="108" class="dropdown-item li" data-valor_opcao="motorista=108" data-texto_botao="108"><label textodepois="1"><input type="checkbox" checked="1">108-EZEQUIAS PIRES DA SILVA</label></li>
                                                                                            <li opcoes_texto_opcao="109-GILBERTO CARLOS BEZERRA" opcoes_valor_opcao="motorista=109" opcoes_texto_botao="109" class="dropdown-item li" data-valor_opcao="motorista=109" data-texto_botao="109"><label textodepois="1"><input type="checkbox" checked="1">109-GILBERTO CARLOS BEZERRA</label></li>
                                                                                            <li opcoes_texto_opcao="110-IVANOR DOS SANTOS MARTINS" opcoes_valor_opcao="motorista=110" opcoes_texto_botao="110" class="dropdown-item li" data-valor_opcao="motorista=110" data-texto_botao="110"><label textodepois="1"><input type="checkbox" checked="1">110-IVANOR DOS SANTOS MARTINS</label></li>
                                                                                            <li opcoes_texto_opcao="111-JEFFERSON MARCELO DA CRUZ" opcoes_valor_opcao="motorista=111" opcoes_texto_botao="111" class="dropdown-item li" data-valor_opcao="motorista=111" data-texto_botao="111"><label textodepois="1"><input type="checkbox" checked="1">111-JEFFERSON MARCELO DA CRUZ</label></li>
                                                                                            <li opcoes_texto_opcao="112-JOAO PAULO FIGUEIREDO" opcoes_valor_opcao="motorista=112" opcoes_texto_botao="112" class="dropdown-item li" data-valor_opcao="motorista=112" data-texto_botao="112"><label textodepois="1"><input type="checkbox" checked="1">112-JOAO PAULO FIGUEIREDO</label></li>
                                                                                            <li opcoes_texto_opcao="113-MILTON DA SILVA SANTOS" opcoes_valor_opcao="motorista=113" opcoes_texto_botao="113" class="dropdown-item li" data-valor_opcao="motorista=113" data-texto_botao="113"><label textodepois="1"><input type="checkbox" checked="1">113-MILTON DA SILVA SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="114-NEYMAR CESAR MANDRICK FORTE" opcoes_valor_opcao="motorista=114" opcoes_texto_botao="114" class="dropdown-item li" data-valor_opcao="motorista=114" data-texto_botao="114"><label textodepois="1"><input type="checkbox" checked="1">114-NEYMAR CESAR MANDRICK FORTE</label></li>
                                                                                            <li opcoes_texto_opcao="115-SIDNEI LUCHETTI" opcoes_valor_opcao="motorista=115" opcoes_texto_botao="115" class="dropdown-item li" data-valor_opcao="motorista=115" data-texto_botao="115"><label textodepois="1"><input type="checkbox" checked="1">115-SIDNEI LUCHETTI</label></li>
                                                                                            <li opcoes_texto_opcao="116-SILVANO RODRIGUES DE OLIVEIRA" opcoes_valor_opcao="motorista=116" opcoes_texto_botao="116" class="dropdown-item li" data-valor_opcao="motorista=116" data-texto_botao="116"><label textodepois="1"><input type="checkbox" checked="1">116-SILVANO RODRIGUES DE OLIVEIRA</label></li>
                                                                                            <li opcoes_texto_opcao="118-WILSON ALVES" opcoes_valor_opcao="motorista=118" opcoes_texto_botao="118" class="dropdown-item li" data-valor_opcao="motorista=118" data-texto_botao="118"><label textodepois="1"><input type="checkbox" checked="1">118-WILSON ALVES</label></li>
                                                                                            <li opcoes_texto_opcao="124-JUNIOR CEZAR CASTRO DA SILVA" opcoes_valor_opcao="motorista=124" opcoes_texto_botao="124" class="dropdown-item li" data-valor_opcao="motorista=124" data-texto_botao="124"><label textodepois="1"><input type="checkbox" checked="1">124-JUNIOR CEZAR CASTRO DA SILVA</label></li>
                                                                                            <li opcoes_texto_opcao="125-LUIZ FERNANDO CORREIA NASCIMENTO" opcoes_valor_opcao="motorista=125" opcoes_texto_botao="125" class="dropdown-item li" data-valor_opcao="motorista=125" data-texto_botao="125"><label textodepois="1"><input type="checkbox" checked="1">125-LUIZ FERNANDO CORREIA NASCIMENTO</label></li>
                                                                                            <li opcoes_texto_opcao="126-ELVIO FERREIRA DE LIMA" opcoes_valor_opcao="motorista=126" opcoes_texto_botao="126" class="dropdown-item li" data-valor_opcao="motorista=126" data-texto_botao="126"><label textodepois="1"><input type="checkbox" checked="1">126-ELVIO FERREIRA DE LIMA</label></li>
                                                                                            <li opcoes_texto_opcao="127-ROGERIO ANDRADE SILVA" opcoes_valor_opcao="motorista=127" opcoes_texto_botao="127" class="dropdown-item li" data-valor_opcao="motorista=127" data-texto_botao="127"><label textodepois="1"><input type="checkbox" checked="1">127-ROGERIO ANDRADE SILVA</label></li>
                                                                                            <li opcoes_texto_opcao="128-VOLMIR CEREZOLI" opcoes_valor_opcao="motorista=128" opcoes_texto_botao="128" class="dropdown-item li" data-valor_opcao="motorista=128" data-texto_botao="128"><label textodepois="1"><input type="checkbox" checked="1">128-VOLMIR CEREZOLI</label></li>
                                                                                            <li opcoes_texto_opcao="129-ROGERIO MOLINARI" opcoes_valor_opcao="motorista=129" opcoes_texto_botao="129" class="dropdown-item li" data-valor_opcao="motorista=129" data-texto_botao="129"><label textodepois="1"><input type="checkbox" checked="1">129-ROGERIO MOLINARI</label></li>
                                                                                            <li opcoes_texto_opcao="130-ISRAEL LEPEK" opcoes_valor_opcao="motorista=130" opcoes_texto_botao="130" class="dropdown-item li" data-valor_opcao="motorista=130" data-texto_botao="130"><label textodepois="1"><input type="checkbox" checked="1">130-ISRAEL LEPEK</label></li>
                                                                                            <li opcoes_texto_opcao="131-VOLMIR CEREZOLI" opcoes_valor_opcao="motorista=131" opcoes_texto_botao="131" class="dropdown-item li" data-valor_opcao="motorista=131" data-texto_botao="131"><label textodepois="1"><input type="checkbox" checked="1">131-VOLMIR CEREZOLI</label></li>
                                                                                            <li opcoes_texto_opcao="132-ROGERIO MOLINARI" opcoes_valor_opcao="motorista=132" opcoes_texto_botao="132" class="dropdown-item li" data-valor_opcao="motorista=132" data-texto_botao="132"><label textodepois="1"><input type="checkbox" checked="1">132-ROGERIO MOLINARI</label></li>
                                                                                            <li opcoes_texto_opcao="133-ISRAEL LEPEK" opcoes_valor_opcao="motorista=133" opcoes_texto_botao="133" class="dropdown-item li" data-valor_opcao="motorista=133" data-texto_botao="133"><label textodepois="1"><input type="checkbox" checked="1">133-ISRAEL LEPEK</label></li>
                                                                                            <li opcoes_texto_opcao="135-MARCOS DOS SANTOS" opcoes_valor_opcao="motorista=135" opcoes_texto_botao="135" class="dropdown-item li" data-valor_opcao="motorista=135" data-texto_botao="135"><label textodepois="1"><input type="checkbox" checked="1">135-MARCOS DOS SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="136-FABIO DE OLIVEIRA DOS SANTOS" opcoes_valor_opcao="motorista=136" opcoes_texto_botao="136" class="dropdown-item li" data-valor_opcao="motorista=136" data-texto_botao="136"><label textodepois="1"><input type="checkbox" checked="1">136-FABIO DE OLIVEIRA DOS SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="137-ANTONIO GESSER JANUARIO" opcoes_valor_opcao="motorista=137" opcoes_texto_botao="137" class="dropdown-item li" data-valor_opcao="motorista=137" data-texto_botao="137"><label textodepois="1"><input type="checkbox" checked="1">137-ANTONIO GESSER JANUARIO</label></li>
                                                                                            <li opcoes_texto_opcao="138-S.G SELERI  TRANSPORTES ME " opcoes_valor_opcao="motorista=138" opcoes_texto_botao="138" class="dropdown-item li" data-valor_opcao="motorista=138" data-texto_botao="138"><label textodepois="1"><input type="checkbox" checked="1">138-S.G SELERI  TRANSPORTES ME</label></li>
                                                                                            <li opcoes_texto_opcao="139-PAULO HENRIQUE CARVALHO" opcoes_valor_opcao="motorista=139" opcoes_texto_botao="139" class="dropdown-item li" data-valor_opcao="motorista=139" data-texto_botao="139"><label textodepois="1"><input type="checkbox" checked="1">139-PAULO HENRIQUE CARVALHO</label></li>
                                                                                            <li opcoes_texto_opcao="141-ANSELMO" opcoes_valor_opcao="motorista=141" opcoes_texto_botao="141" class="dropdown-item li" data-valor_opcao="motorista=141" data-texto_botao="141"><label textodepois="1"><input type="checkbox" checked="1">141-ANSELMO</label></li>
                                                                                            <li opcoes_texto_opcao="150-CLAUDIONOR PAULA DAS CHAGAS" opcoes_valor_opcao="motorista=150" opcoes_texto_botao="150" class="dropdown-item li" data-valor_opcao="motorista=150" data-texto_botao="150"><label textodepois="1"><input type="checkbox" checked="1">150-CLAUDIONOR PAULA DAS CHAGAS</label></li>
                                                                                            <li opcoes_texto_opcao="152-ODAIR JUSTINO" opcoes_valor_opcao="motorista=152" opcoes_texto_botao="152" class="dropdown-item li" data-valor_opcao="motorista=152" data-texto_botao="152"><label textodepois="1"><input type="checkbox" checked="1">152-ODAIR JUSTINO</label></li>
                                                                                            <li opcoes_texto_opcao="158-CLAUDIO CIRILLO" opcoes_valor_opcao="motorista=158" opcoes_texto_botao="158" class="dropdown-item li" data-valor_opcao="motorista=158" data-texto_botao="158"><label textodepois="1"><input type="checkbox" checked="1">158-CLAUDIO CIRILLO</label></li>
                                                                                            <li opcoes_texto_opcao="180-ANTONIO SERGIO FRANCA" opcoes_valor_opcao="motorista=180" opcoes_texto_botao="180" class="dropdown-item li" data-valor_opcao="motorista=180" data-texto_botao="180"><label textodepois="1"><input type="checkbox" checked="1">180-ANTONIO SERGIO FRANCA</label></li>
                                                                                            <li opcoes_texto_opcao="181-RICARDO JOSE CORREA" opcoes_valor_opcao="motorista=181" opcoes_texto_botao="181" class="dropdown-item li" data-valor_opcao="motorista=181" data-texto_botao="181"><label textodepois="1"><input type="checkbox" checked="1">181-RICARDO JOSE CORREA</label></li>
                                                                                            <li opcoes_texto_opcao="187-JOSE APARECIDO DE OLIVEIRA" opcoes_valor_opcao="motorista=187" opcoes_texto_botao="187" class="dropdown-item li" data-valor_opcao="motorista=187" data-texto_botao="187"><label textodepois="1"><input type="checkbox" checked="1">187-JOSE APARECIDO DE OLIVEIRA</label></li>
                                                                                            <li opcoes_texto_opcao="188-SEBASTI?O CAMARGO" opcoes_valor_opcao="motorista=188" opcoes_texto_botao="188" class="dropdown-item li" data-valor_opcao="motorista=188" data-texto_botao="188"><label textodepois="1"><input type="checkbox" checked="1">188-SEBASTI?O CAMARGO</label></li>
                                                                                            <li opcoes_texto_opcao="189-EDUARDO ALVES" opcoes_valor_opcao="motorista=189" opcoes_texto_botao="189" class="dropdown-item li" data-valor_opcao="motorista=189" data-texto_botao="189"><label textodepois="1"><input type="checkbox" checked="1">189-EDUARDO ALVES</label></li>
                                                                                            <li opcoes_texto_opcao="190-MARIONEI SALES FERREIRA " opcoes_valor_opcao="motorista=190" opcoes_texto_botao="190" class="dropdown-item li" data-valor_opcao="motorista=190" data-texto_botao="190"><label textodepois="1"><input type="checkbox" checked="1">190-MARIONEI SALES FERREIRA</label></li>
                                                                                            <li opcoes_texto_opcao="192-PAULO SERGIO SILVA GUTIERREZ" opcoes_valor_opcao="motorista=192" opcoes_texto_botao="192" class="dropdown-item li" data-valor_opcao="motorista=192" data-texto_botao="192"><label textodepois="1"><input type="checkbox" checked="1">192-PAULO SERGIO SILVA GUTIERREZ</label></li>
                                                                                            <li opcoes_texto_opcao="194-RIZIEL FRAGOSO RAMOS" opcoes_valor_opcao="motorista=194" opcoes_texto_botao="194" class="dropdown-item li" data-valor_opcao="motorista=194" data-texto_botao="194"><label textodepois="1"><input type="checkbox" checked="1">194-RIZIEL FRAGOSO RAMOS</label></li>
                                                                                            <li opcoes_texto_opcao="198-LEANDRO LIMA SANTIAGO" opcoes_valor_opcao="motorista=198" opcoes_texto_botao="198" class="dropdown-item li" data-valor_opcao="motorista=198" data-texto_botao="198"><label textodepois="1"><input type="checkbox" checked="1">198-LEANDRO LIMA SANTIAGO</label></li>
                                                                                            <li opcoes_texto_opcao="201-PAULO GARCIA JUNIOR" opcoes_valor_opcao="motorista=201" opcoes_texto_botao="201" class="dropdown-item li" data-valor_opcao="motorista=201" data-texto_botao="201"><label textodepois="1"><input type="checkbox" checked="1">201-PAULO GARCIA JUNIOR</label></li>
                                                                                            <li opcoes_texto_opcao="203-ELIZEU DE JESUS DOS REIS" opcoes_valor_opcao="motorista=203" opcoes_texto_botao="203" class="dropdown-item li" data-valor_opcao="motorista=203" data-texto_botao="203"><label textodepois="1"><input type="checkbox" checked="1">203-ELIZEU DE JESUS DOS REIS</label></li>
                                                                                            <li opcoes_texto_opcao="220-IRDEU DE JESUS SANTOS" opcoes_valor_opcao="motorista=220" opcoes_texto_botao="220" class="dropdown-item li" data-valor_opcao="motorista=220" data-texto_botao="220"><label textodepois="1"><input type="checkbox" checked="1">220-IRDEU DE JESUS SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="222-CARLOS CESAR SANDI" opcoes_valor_opcao="motorista=222" opcoes_texto_botao="222" class="dropdown-item li" data-valor_opcao="motorista=222" data-texto_botao="222"><label textodepois="1"><input type="checkbox" checked="1">222-CARLOS CESAR SANDI</label></li>
                                                                                            <li opcoes_texto_opcao="22637-ANDERSON SAFFIOTTI" opcoes_valor_opcao="motorista=22637" opcoes_texto_botao="22637" class="dropdown-item li" data-valor_opcao="motorista=22637" data-texto_botao="22637"><label textodepois="1"><input type="checkbox" checked="1">22637-ANDERSON SAFFIOTTI</label></li>
                                                                                            <li opcoes_texto_opcao="230-VALNEI BANDURSKI" opcoes_valor_opcao="motorista=230" opcoes_texto_botao="230" class="dropdown-item li" data-valor_opcao="motorista=230" data-texto_botao="230"><label textodepois="1"><input type="checkbox" checked="1">230-VALNEI BANDURSKI</label></li>
                                                                                            <li opcoes_texto_opcao="231-DEVOLUCAO " opcoes_valor_opcao="motorista=231" opcoes_texto_botao="231" class="dropdown-item li" data-valor_opcao="motorista=231" data-texto_botao="231"><label textodepois="1"><input type="checkbox" checked="1">231-DEVOLUCAO</label></li>
                                                                                            <li opcoes_texto_opcao="260-ALEXANDRE AGOSTINIS" opcoes_valor_opcao="motorista=260" opcoes_texto_botao="260" class="dropdown-item li" data-valor_opcao="motorista=260" data-texto_botao="260"><label textodepois="1"><input type="checkbox" checked="1">260-ALEXANDRE AGOSTINIS</label></li>
                                                                                            <li opcoes_texto_opcao="263-JOSE WELLINGTON CORREIA LIMA " opcoes_valor_opcao="motorista=263" opcoes_texto_botao="263" class="dropdown-item li" data-valor_opcao="motorista=263" data-texto_botao="263"><label textodepois="1"><input type="checkbox" checked="1">263-JOSE WELLINGTON CORREIA LIMA</label></li>
                                                                                            <li opcoes_texto_opcao="3-SILVINO MOREIRA" opcoes_valor_opcao="motorista=3" opcoes_texto_botao="3" class="dropdown-item li" data-valor_opcao="motorista=3" data-texto_botao="3"><label textodepois="1"><input type="checkbox" checked="1">3-SILVINO MOREIRA</label></li>
                                                                                            <li opcoes_texto_opcao="555-VALDEMIR PIRES" opcoes_valor_opcao="motorista=555" opcoes_texto_botao="555" class="dropdown-item li" data-valor_opcao="motorista=555" data-texto_botao="555"><label textodepois="1"><input type="checkbox" checked="1">555-VALDEMIR PIRES</label></li>
                                                                                            <li opcoes_texto_opcao="558-LUIS CESAR DE SOUZA" opcoes_valor_opcao="motorista=558" opcoes_texto_botao="558" class="dropdown-item li" data-valor_opcao="motorista=558" data-texto_botao="558"><label textodepois="1"><input type="checkbox" checked="1">558-LUIS CESAR DE SOUZA</label></li>
                                                                                            <li opcoes_texto_opcao="559-ZOILO CORREA LEMOS JUNIOR" opcoes_valor_opcao="motorista=559" opcoes_texto_botao="559" class="dropdown-item li" data-valor_opcao="motorista=559" data-texto_botao="559"><label textodepois="1"><input type="checkbox" checked="1">559-ZOILO CORREA LEMOS JUNIOR</label></li>
                                                                                            <li opcoes_texto_opcao="560-ADENILSON APARECIDO DA SILVA" opcoes_valor_opcao="motorista=560" opcoes_texto_botao="560" class="dropdown-item li" data-valor_opcao="motorista=560" data-texto_botao="560"><label textodepois="1"><input type="checkbox" checked="1">560-ADENILSON APARECIDO DA SILVA</label></li>
                                                                                            <li opcoes_texto_opcao="562-CLAUDIANO RIBEIRO SOARES" opcoes_valor_opcao="motorista=562" opcoes_texto_botao="562" class="dropdown-item li" data-valor_opcao="motorista=562" data-texto_botao="562"><label textodepois="1"><input type="checkbox" checked="1">562-CLAUDIANO RIBEIRO SOARES</label></li>
                                                                                            <li opcoes_texto_opcao="563-MARCOS LEANDRO DA FONSECA" opcoes_valor_opcao="motorista=563" opcoes_texto_botao="563" class="dropdown-item li" data-valor_opcao="motorista=563" data-texto_botao="563"><label textodepois="1"><input type="checkbox" checked="1">563-MARCOS LEANDRO DA FONSECA</label></li>
                                                                                            <li opcoes_texto_opcao="564-EVANDRO SIQUEIRA" opcoes_valor_opcao="motorista=564" opcoes_texto_botao="564" class="dropdown-item li" data-valor_opcao="motorista=564" data-texto_botao="564"><label textodepois="1"><input type="checkbox" checked="1">564-EVANDRO SIQUEIRA</label></li>
                                                                                            <li opcoes_texto_opcao="565-ALTAIR GONCALVES AGUIAR " opcoes_valor_opcao="motorista=565" opcoes_texto_botao="565" class="dropdown-item li" data-valor_opcao="motorista=565" data-texto_botao="565"><label textodepois="1"><input type="checkbox" checked="1">565-ALTAIR GONCALVES AGUIAR</label></li>
                                                                                            <li opcoes_texto_opcao="567-HELIO DIAS DE OLIVEIRA " opcoes_valor_opcao="motorista=567" opcoes_texto_botao="567" class="dropdown-item li" data-valor_opcao="motorista=567" data-texto_botao="567"><label textodepois="1"><input type="checkbox" checked="1">567-HELIO DIAS DE OLIVEIRA</label></li>
                                                                                            <li opcoes_texto_opcao="570-ANDRE MORAES CARDOSO DE SA" opcoes_valor_opcao="motorista=570" opcoes_texto_botao="570" class="dropdown-item li" data-valor_opcao="motorista=570" data-texto_botao="570"><label textodepois="1"><input type="checkbox" checked="1">570-ANDRE MORAES CARDOSO DE SA</label></li>
                                                                                            <li opcoes_texto_opcao="571-R R B TRANSPORTES E LOGISTICA LTDA" opcoes_valor_opcao="motorista=571" opcoes_texto_botao="571" class="dropdown-item li" data-valor_opcao="motorista=571" data-texto_botao="571"><label textodepois="1"><input type="checkbox" checked="1">571-R R B TRANSPORTES E LOGISTICA LTDA</label></li>
                                                                                            <li opcoes_texto_opcao="572-RODRIGO DE BARROS " opcoes_valor_opcao="motorista=572" opcoes_texto_botao="572" class="dropdown-item li" data-valor_opcao="motorista=572" data-texto_botao="572"><label textodepois="1"><input type="checkbox" checked="1">572-RODRIGO DE BARROS</label></li>
                                                                                            <li opcoes_texto_opcao="575-NEY FRANCISCO FORTE " opcoes_valor_opcao="motorista=575" opcoes_texto_botao="575" class="dropdown-item li" data-valor_opcao="motorista=575" data-texto_botao="575"><label textodepois="1"><input type="checkbox" checked="1">575-NEY FRANCISCO FORTE</label></li>
                                                                                            <li opcoes_texto_opcao="579-ROGERIO DE FREITAS" opcoes_valor_opcao="motorista=579" opcoes_texto_botao="579" class="dropdown-item li" data-valor_opcao="motorista=579" data-texto_botao="579"><label textodepois="1"><input type="checkbox" checked="1">579-ROGERIO DE FREITAS</label></li>
                                                                                            <li opcoes_texto_opcao="580-EDNEI BORGES COSTAS" opcoes_valor_opcao="motorista=580" opcoes_texto_botao="580" class="dropdown-item li" data-valor_opcao="motorista=580" data-texto_botao="580"><label textodepois="1"><input type="checkbox" checked="1">580-EDNEI BORGES COSTAS</label></li>
                                                                                            <li opcoes_texto_opcao="581-EDERSON" opcoes_valor_opcao="motorista=581" opcoes_texto_botao="581" class="dropdown-item li" data-valor_opcao="motorista=581" data-texto_botao="581"><label textodepois="1"><input type="checkbox" checked="1">581-EDERSON</label></li>
                                                                                            <li opcoes_texto_opcao="582-ANTONIO GESSER JANUARIO" opcoes_valor_opcao="motorista=582" opcoes_texto_botao="582" class="dropdown-item li" data-valor_opcao="motorista=582" data-texto_botao="582"><label textodepois="1"><input type="checkbox" checked="1">582-ANTONIO GESSER JANUARIO</label></li>
                                                                                            <li opcoes_texto_opcao="586-NEY " opcoes_valor_opcao="motorista=586" opcoes_texto_botao="586" class="dropdown-item li" data-valor_opcao="motorista=586" data-texto_botao="586"><label textodepois="1"><input type="checkbox" checked="1">586-NEY</label></li>
                                                                                            <li opcoes_texto_opcao="588-JHONY HENRIQUE" opcoes_valor_opcao="motorista=588" opcoes_texto_botao="588" class="dropdown-item li" data-valor_opcao="motorista=588" data-texto_botao="588"><label textodepois="1"><input type="checkbox" checked="1">588-JHONY HENRIQUE</label></li>
                                                                                            <li opcoes_texto_opcao="592-EMERSON LEOPOLDO" opcoes_valor_opcao="motorista=592" opcoes_texto_botao="592" class="dropdown-item li" data-valor_opcao="motorista=592" data-texto_botao="592"><label textodepois="1"><input type="checkbox" checked="1">592-EMERSON LEOPOLDO</label></li>
                                                                                            <li opcoes_texto_opcao="610-ANDRE MARTINS RODRIGUES" opcoes_valor_opcao="motorista=610" opcoes_texto_botao="610" class="dropdown-item li" data-valor_opcao="motorista=610" data-texto_botao="610"><label textodepois="1"><input type="checkbox" checked="1">610-ANDRE MARTINS RODRIGUES</label></li>
                                                                                            <li opcoes_texto_opcao="611-MARCIEL GONCALVES DE ARAUJO" opcoes_valor_opcao="motorista=611" opcoes_texto_botao="611" class="dropdown-item li" data-valor_opcao="motorista=611" data-texto_botao="611"><label textodepois="1"><input type="checkbox" checked="1">611-MARCIEL GONCALVES DE ARAUJO</label></li>
                                                                                            <li opcoes_texto_opcao="621-GELSON BARRETO DA COSTA" opcoes_valor_opcao="motorista=621" opcoes_texto_botao="621" class="dropdown-item li" data-valor_opcao="motorista=621" data-texto_botao="621"><label textodepois="1"><input type="checkbox" checked="1">621-GELSON BARRETO DA COSTA</label></li>
                                                                                            <li opcoes_texto_opcao="627-FABIO DE MELO DOS SANTOS" opcoes_valor_opcao="motorista=627" opcoes_texto_botao="627" class="dropdown-item li" data-valor_opcao="motorista=627" data-texto_botao="627"><label textodepois="1"><input type="checkbox" checked="1">627-FABIO DE MELO DOS SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="628-GILSON CRUZ" opcoes_valor_opcao="motorista=628" opcoes_texto_botao="628" class="dropdown-item li" data-valor_opcao="motorista=628" data-texto_botao="628"><label textodepois="1"><input type="checkbox" checked="1">628-GILSON CRUZ</label></li>
                                                                                            <li opcoes_texto_opcao="630-MARCELO ROSA SOARES" opcoes_valor_opcao="motorista=630" opcoes_texto_botao="630" class="dropdown-item li" data-valor_opcao="motorista=630" data-texto_botao="630"><label textodepois="1"><input type="checkbox" checked="1">630-MARCELO ROSA SOARES</label></li>
                                                                                            <li opcoes_texto_opcao="632-HUDSON BATISTA SILVA" opcoes_valor_opcao="motorista=632" opcoes_texto_botao="632" class="dropdown-item li" data-valor_opcao="motorista=632" data-texto_botao="632"><label textodepois="1"><input type="checkbox" checked="1">632-HUDSON BATISTA SILVA</label></li>
                                                                                            <li opcoes_texto_opcao="633-DEINE RODRIGO DE OLIVEIRA" opcoes_valor_opcao="motorista=633" opcoes_texto_botao="633" class="dropdown-item li" data-valor_opcao="motorista=633" data-texto_botao="633"><label textodepois="1"><input type="checkbox" checked="1">633-DEINE RODRIGO DE OLIVEIRA</label></li>
                                                                                            <li opcoes_texto_opcao="634-SIDNEI LUIZ CERVI" opcoes_valor_opcao="motorista=634" opcoes_texto_botao="634" class="dropdown-item li" data-valor_opcao="motorista=634" data-texto_botao="634"><label textodepois="1"><input type="checkbox" checked="1">634-SIDNEI LUIZ CERVI</label></li>
                                                                                            <li opcoes_texto_opcao="638-V.P.CRIST-TRANSPORTES " opcoes_valor_opcao="motorista=638" opcoes_texto_botao="638" class="dropdown-item li" data-valor_opcao="motorista=638" data-texto_botao="638"><label textodepois="1"><input type="checkbox" checked="1">638-V.P.CRIST-TRANSPORTES</label></li>
                                                                                            <li opcoes_texto_opcao="639-CLAUDINEI ALVES DE FREITAS" opcoes_valor_opcao="motorista=639" opcoes_texto_botao="639" class="dropdown-item li" data-valor_opcao="motorista=639" data-texto_botao="639"><label textodepois="1"><input type="checkbox" checked="1">639-CLAUDINEI ALVES DE FREITAS</label></li>
                                                                                            <li opcoes_texto_opcao="640-JAIR SCHLICKMANN" opcoes_valor_opcao="motorista=640" opcoes_texto_botao="640" class="dropdown-item li" data-valor_opcao="motorista=640" data-texto_botao="640"><label textodepois="1"><input type="checkbox" checked="1">640-JAIR SCHLICKMANN</label></li>
                                                                                            <li opcoes_texto_opcao="641-JOSE APARECIDO DA SILVA " opcoes_valor_opcao="motorista=641" opcoes_texto_botao="641" class="dropdown-item li" data-valor_opcao="motorista=641" data-texto_botao="641"><label textodepois="1"><input type="checkbox" checked="1">641-JOSE APARECIDO DA SILVA</label></li>
                                                                                            <li opcoes_texto_opcao="642-T R A LONDRINA -TRASNPORTES DE CARGAS " opcoes_valor_opcao="motorista=642" opcoes_texto_botao="642" class="dropdown-item li" data-valor_opcao="motorista=642" data-texto_botao="642"><label textodepois="1"><input type="checkbox" checked="1">642-T R A LONDRINA -TRASNPORTES DE CARGAS</label></li>
                                                                                            <li opcoes_texto_opcao="643-R.F LOSS TRANSPORTES " opcoes_valor_opcao="motorista=643" opcoes_texto_botao="643" class="dropdown-item li" data-valor_opcao="motorista=643" data-texto_botao="643"><label textodepois="1"><input type="checkbox" checked="1">643-R.F LOSS TRANSPORTES</label></li>
                                                                                            <li opcoes_texto_opcao="650-SIDNEI LUIZ CERVI" opcoes_valor_opcao="motorista=650" opcoes_texto_botao="650" class="dropdown-item li" data-valor_opcao="motorista=650" data-texto_botao="650"><label textodepois="1"><input type="checkbox" checked="1">650-SIDNEI LUIZ CERVI</label></li>
                                                                                            <li opcoes_texto_opcao="651-SAMUEL DE ARRUDA " opcoes_valor_opcao="motorista=651" opcoes_texto_botao="651" class="dropdown-item li" data-valor_opcao="motorista=651" data-texto_botao="651"><label textodepois="1"><input type="checkbox" checked="1">651-SAMUEL DE ARRUDA</label></li>
                                                                                            <li opcoes_texto_opcao="652-CLAUDENIR DIAS DE OLIVEIRA " opcoes_valor_opcao="motorista=652" opcoes_texto_botao="652" class="dropdown-item li" data-valor_opcao="motorista=652" data-texto_botao="652"><label textodepois="1"><input type="checkbox" checked="1">652-CLAUDENIR DIAS DE OLIVEIRA</label></li>
                                                                                            <li opcoes_texto_opcao="653-TIAGO APARECIDO LEONEL" opcoes_valor_opcao="motorista=653" opcoes_texto_botao="653" class="dropdown-item li" data-valor_opcao="motorista=653" data-texto_botao="653"><label textodepois="1"><input type="checkbox" checked="1">653-TIAGO APARECIDO LEONEL</label></li>
                                                                                            <li opcoes_texto_opcao="654-PAULO CEZAR RODRIGUES DAS CHAGAS " opcoes_valor_opcao="motorista=654" opcoes_texto_botao="654" class="dropdown-item li" data-valor_opcao="motorista=654" data-texto_botao="654"><label textodepois="1"><input type="checkbox" checked="1">654-PAULO CEZAR RODRIGUES DAS CHAGAS</label></li>
                                                                                            <li opcoes_texto_opcao="655-JEAN MARIANO DOS SANTOS " opcoes_valor_opcao="motorista=655" opcoes_texto_botao="655" class="dropdown-item li" data-valor_opcao="motorista=655" data-texto_botao="655"><label textodepois="1"><input type="checkbox" checked="1">655-JEAN MARIANO DOS SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="656-MARCIO ANDERSON MASSUCHINI" opcoes_valor_opcao="motorista=656" opcoes_texto_botao="656" class="dropdown-item li" data-valor_opcao="motorista=656" data-texto_botao="656"><label textodepois="1"><input type="checkbox" checked="1">656-MARCIO ANDERSON MASSUCHINI</label></li>
                                                                                            <li opcoes_texto_opcao="77-DENILSON VIDAL DOS SANTOS" opcoes_valor_opcao="motorista=77" opcoes_texto_botao="77" class="dropdown-item li" data-valor_opcao="motorista=77" data-texto_botao="77"><label textodepois="1"><input type="checkbox" checked="1">77-DENILSON VIDAL DOS SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="78-TOLEDO E TRANSPORTES  EIRELI" opcoes_valor_opcao="motorista=78" opcoes_texto_botao="78" class="dropdown-item li" data-valor_opcao="motorista=78" data-texto_botao="78"><label textodepois="1"><input type="checkbox" checked="1">78-TOLEDO E TRANSPORTES  EIRELI</label></li>
                                                                                            <li opcoes_texto_opcao="79-LEONARDO DOS SANTOS TASSI" opcoes_valor_opcao="motorista=79" opcoes_texto_botao="79" class="dropdown-item li" data-valor_opcao="motorista=79" data-texto_botao="79"><label textodepois="1"><input type="checkbox" checked="1">79-LEONARDO DOS SANTOS TASSI</label></li>
                                                                                            <li opcoes_texto_opcao="80-MARCO ANTONIO LOPES" opcoes_valor_opcao="motorista=80" opcoes_texto_botao="80" class="dropdown-item li" data-valor_opcao="motorista=80" data-texto_botao="80"><label textodepois="1"><input type="checkbox" checked="1">80-MARCO ANTONIO LOPES</label></li>
                                                                                            <li opcoes_texto_opcao="81-M H FEITOSA-TRANSP E LOGISTICA EIRELI" opcoes_valor_opcao="motorista=81" opcoes_texto_botao="81" class="dropdown-item li" data-valor_opcao="motorista=81" data-texto_botao="81"><label textodepois="1"><input type="checkbox" checked="1">81-M H FEITOSA-TRANSP E LOGISTICA EIRELI</label></li>
                                                                                            <li opcoes_texto_opcao="82-SEBASTIAO APARECIDO SOUZA" opcoes_valor_opcao="motorista=82" opcoes_texto_botao="82" class="dropdown-item li" data-valor_opcao="motorista=82" data-texto_botao="82"><label textodepois="1"><input type="checkbox" checked="1">82-SEBASTIAO APARECIDO SOUZA</label></li>
                                                                                            <li opcoes_texto_opcao="83-S A DA CONCEIC?O TRANSPORTES RODOVIARIOS" opcoes_valor_opcao="motorista=83" opcoes_texto_botao="83" class="dropdown-item li" data-valor_opcao="motorista=83" data-texto_botao="83"><label textodepois="1"><input type="checkbox" checked="1">83-S A DA CONCEIC?O TRANSPORTES RODOVIARIOS</label></li>
                                                                                            <li opcoes_texto_opcao="84-VANDEMIR RODRIGUES" opcoes_valor_opcao="motorista=84" opcoes_texto_botao="84" class="dropdown-item li" data-valor_opcao="motorista=84" data-texto_botao="84"><label textodepois="1"><input type="checkbox" checked="1">84-VANDEMIR RODRIGUES</label></li>
                                                                                            <li opcoes_texto_opcao="85-THIAGO ROBERTO BATISTA LEITE" opcoes_valor_opcao="motorista=85" opcoes_texto_botao="85" class="dropdown-item li" data-valor_opcao="motorista=85" data-texto_botao="85"><label textodepois="1"><input type="checkbox" checked="1">85-THIAGO ROBERTO BATISTA LEITE</label></li>
                                                                                            <li opcoes_texto_opcao="86-HELIO FERREIRA LIMA" opcoes_valor_opcao="motorista=86" opcoes_texto_botao="86" class="dropdown-item li" data-valor_opcao="motorista=86" data-texto_botao="86"><label textodepois="1"><input type="checkbox" checked="1">86-HELIO FERREIRA LIMA</label></li>
                                                                                            <li opcoes_texto_opcao="87-CESAR DA SILVA MOTTA" opcoes_valor_opcao="motorista=87" opcoes_texto_botao="87" class="dropdown-item li" data-valor_opcao="motorista=87" data-texto_botao="87"><label textodepois="1"><input type="checkbox" checked="1">87-CESAR DA SILVA MOTTA</label></li>
                                                                                            <li opcoes_texto_opcao="88-JOSE APARECIDO" opcoes_valor_opcao="motorista=88" opcoes_texto_botao="88" class="dropdown-item li" data-valor_opcao="motorista=88" data-texto_botao="88"><label textodepois="1"><input type="checkbox" checked="1">88-JOSE APARECIDO</label></li>
                                                                                            <li opcoes_texto_opcao="89-JOSIEL PROCOPIO GOMES" opcoes_valor_opcao="motorista=89" opcoes_texto_botao="89" class="dropdown-item li" data-valor_opcao="motorista=89" data-texto_botao="89"><label textodepois="1"><input type="checkbox" checked="1">89-JOSIEL PROCOPIO GOMES</label></li>
                                                                                            </ul>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="div_opcao_controles_btns_img col-md-auto w-auto"></div>
                                                                                </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                        <div class="col-auto mt-2 div_visao col">
                                                                            <div funcao_inclusao="window.fnsisjd.inserir_visao_pesquisa({elemento:this})" funcao_exclusao="window.fnsisjd.deletar_controles({elemento:this})" class="card">
                                                                                <div class="card-header">Rca</div>
                                                                                <div class="card-body">
                                                                                <div class="row">
                                                                                    <div class="col">
                                                                                        <div label="Rca" visao="Rca" class="condicionante div_combobox" tipo_inputs="checkbox" selecionar_todos="1" multiplo="1" filtro="1" tem_inputs="1" placeholder="(Selecione)" classe_botao="btn-dark" num_max_texto_botao="5" funcao_filtro="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                            <button type="button" class="btn dropdown-toggle btn-dark" data-bs-toggle="dropdown" aria-expanded="false" num_max_texto_botao="5" data-bs-auto-close="outside">Todos (86)</button>
                                                                                            <ul class="dropdown-menu" onclick="window.fnhtml.fndrop.clicou_dropdown(event,this)">
                                                                                            <label class="label_selecionar_todos" textodepois="1"><input type="checkbox" class="input_selecionar_todos" onchange="window.fnhtml.fndrop.selecionou_todos_dropdown(event,this)">Selecionar Todos</label><input type="text" class="input_filtro_dropdown rounded" placeholder="(filtro)" onkeyup="window.fnhtml.fndrop.filtrar_dropdown(this)">
                                                                                            <li opcoes_texto_opcao="1-CARLOS LEMOS " opcoes_valor_opcao="rca=1" opcoes_texto_botao="1" class="dropdown-item li" data-valor_opcao="rca=1" data-texto_botao="1"><label textodepois="1"><input type="checkbox" checked="1">1-CARLOS LEMOS</label></li>
                                                                                            <li opcoes_texto_opcao="101-ANTONIO FURLAN LARA" opcoes_valor_opcao="rca=101" opcoes_texto_botao="101" class="dropdown-item li" data-valor_opcao="rca=101" data-texto_botao="101"><label textodepois="1"><input type="checkbox" checked="1">101-ANTONIO FURLAN LARA</label></li>
                                                                                            <li opcoes_texto_opcao="102-ARAYAN LUIZ SCHIAVINI" opcoes_valor_opcao="rca=102" opcoes_texto_botao="102" class="dropdown-item li" data-valor_opcao="rca=102" data-texto_botao="102"><label textodepois="1"><input type="checkbox" checked="1">102-ARAYAN LUIZ SCHIAVINI</label></li>
                                                                                            <li opcoes_texto_opcao="103-AIRTON MARQUES DOS SANTOS " opcoes_valor_opcao="rca=103" opcoes_texto_botao="103" class="dropdown-item li" data-valor_opcao="rca=103" data-texto_botao="103"><label textodepois="1"><input type="checkbox" checked="1">103-AIRTON MARQUES DOS SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="104-EDSON ANGELO LOREZI" opcoes_valor_opcao="rca=104" opcoes_texto_botao="104" class="dropdown-item li" data-valor_opcao="rca=104" data-texto_botao="104"><label textodepois="1"><input type="checkbox" checked="1">104-EDSON ANGELO LOREZI</label></li>
                                                                                            <li opcoes_texto_opcao="105-DERCIO PEREIRA DA CUNHA" opcoes_valor_opcao="rca=105" opcoes_texto_botao="105" class="dropdown-item li" data-valor_opcao="rca=105" data-texto_botao="105"><label textodepois="1"><input type="checkbox" checked="1">105-DERCIO PEREIRA DA CUNHA</label></li>
                                                                                            <li opcoes_texto_opcao="106-ANTONIO LORENZETTI" opcoes_valor_opcao="rca=106" opcoes_texto_botao="106" class="dropdown-item li" data-valor_opcao="rca=106" data-texto_botao="106"><label textodepois="1"><input type="checkbox" checked="1">106-ANTONIO LORENZETTI</label></li>
                                                                                            <li opcoes_texto_opcao="107-LUIZ CARLOS DE MARCHI" opcoes_valor_opcao="rca=107" opcoes_texto_botao="107" class="dropdown-item li" data-valor_opcao="rca=107" data-texto_botao="107"><label textodepois="1"><input type="checkbox" checked="1">107-LUIZ CARLOS DE MARCHI</label></li>
                                                                                            <li opcoes_texto_opcao="108-ESMAEL MARCELO ULKOWSKI" opcoes_valor_opcao="rca=108" opcoes_texto_botao="108" class="dropdown-item li" data-valor_opcao="rca=108" data-texto_botao="108"><label textodepois="1"><input type="checkbox" checked="1">108-ESMAEL MARCELO ULKOWSKI</label></li>
                                                                                            <li opcoes_texto_opcao="109-ROGERIO MAZZO" opcoes_valor_opcao="rca=109" opcoes_texto_botao="109" class="dropdown-item li" data-valor_opcao="rca=109" data-texto_botao="109"><label textodepois="1"><input type="checkbox" checked="1">109-ROGERIO MAZZO</label></li>
                                                                                            <li opcoes_texto_opcao="110-CLEITON JOSE ESSER" opcoes_valor_opcao="rca=110" opcoes_texto_botao="110" class="dropdown-item li" data-valor_opcao="rca=110" data-texto_botao="110"><label textodepois="1"><input type="checkbox" checked="1">110-CLEITON JOSE ESSER</label></li>
                                                                                            <li opcoes_texto_opcao="111-HAMILTON APARECIDO SILVEIRA" opcoes_valor_opcao="rca=111" opcoes_texto_botao="111" class="dropdown-item li" data-valor_opcao="rca=111" data-texto_botao="111"><label textodepois="1"><input type="checkbox" checked="1">111-HAMILTON APARECIDO SILVEIRA</label></li>
                                                                                            <li opcoes_texto_opcao="112-INACIO SCHLICKMANN" opcoes_valor_opcao="rca=112" opcoes_texto_botao="112" class="dropdown-item li" data-valor_opcao="rca=112" data-texto_botao="112"><label textodepois="1"><input type="checkbox" checked="1">112-INACIO SCHLICKMANN</label></li>
                                                                                            <li opcoes_texto_opcao="113-ADRIANO GARCIA MARIN" opcoes_valor_opcao="rca=113" opcoes_texto_botao="113" class="dropdown-item li" data-valor_opcao="rca=113" data-texto_botao="113"><label textodepois="1"><input type="checkbox" checked="1">113-ADRIANO GARCIA MARIN</label></li>
                                                                                            <li opcoes_texto_opcao="114-ARAYAN SCHIAVINI" opcoes_valor_opcao="rca=114" opcoes_texto_botao="114" class="dropdown-item li" data-valor_opcao="rca=114" data-texto_botao="114"><label textodepois="1"><input type="checkbox" checked="1">114-ARAYAN SCHIAVINI</label></li>
                                                                                            <li opcoes_texto_opcao="115-PATRICIA LOPES" opcoes_valor_opcao="rca=115" opcoes_texto_botao="115" class="dropdown-item li" data-valor_opcao="rca=115" data-texto_botao="115"><label textodepois="1"><input type="checkbox" checked="1">115-PATRICIA LOPES</label></li>
                                                                                            <li opcoes_texto_opcao="116-RUDSON NOE PEREIRA DE LIMA" opcoes_valor_opcao="rca=116" opcoes_texto_botao="116" class="dropdown-item li" data-valor_opcao="rca=116" data-texto_botao="116"><label textodepois="1"><input type="checkbox" checked="1">116-RUDSON NOE PEREIRA DE LIMA</label></li>
                                                                                            <li opcoes_texto_opcao="117-EDSON NUNES" opcoes_valor_opcao="rca=117" opcoes_texto_botao="117" class="dropdown-item li" data-valor_opcao="rca=117" data-texto_botao="117"><label textodepois="1"><input type="checkbox" checked="1">117-EDSON NUNES</label></li>
                                                                                            <li opcoes_texto_opcao="118-ANDERSON" opcoes_valor_opcao="rca=118" opcoes_texto_botao="118" class="dropdown-item li" data-valor_opcao="rca=118" data-texto_botao="118"><label textodepois="1"><input type="checkbox" checked="1">118-ANDERSON</label></li>
                                                                                            <li opcoes_texto_opcao="121-VILMAR ALVES PINTO" opcoes_valor_opcao="rca=121" opcoes_texto_botao="121" class="dropdown-item li" data-valor_opcao="rca=121" data-texto_botao="121"><label textodepois="1"><input type="checkbox" checked="1">121-VILMAR ALVES PINTO</label></li>
                                                                                            <li opcoes_texto_opcao="122-VILMA ROCHA" opcoes_valor_opcao="rca=122" opcoes_texto_botao="122" class="dropdown-item li" data-valor_opcao="rca=122" data-texto_botao="122"><label textodepois="1"><input type="checkbox" checked="1">122-VILMA ROCHA</label></li>
                                                                                            <li opcoes_texto_opcao="123-ALEXSANDRO FURQUIM" opcoes_valor_opcao="rca=123" opcoes_texto_botao="123" class="dropdown-item li" data-valor_opcao="rca=123" data-texto_botao="123"><label textodepois="1"><input type="checkbox" checked="1">123-ALEXSANDRO FURQUIM</label></li>
                                                                                            <li opcoes_texto_opcao="124-EVANDRO LUIZ PROCHOSKI" opcoes_valor_opcao="rca=124" opcoes_texto_botao="124" class="dropdown-item li" data-valor_opcao="rca=124" data-texto_botao="124"><label textodepois="1"><input type="checkbox" checked="1">124-EVANDRO LUIZ PROCHOSKI</label></li>
                                                                                            <li opcoes_texto_opcao="126-JOSE ADRIANO DE FREITAS" opcoes_valor_opcao="rca=126" opcoes_texto_botao="126" class="dropdown-item li" data-valor_opcao="rca=126" data-texto_botao="126"><label textodepois="1"><input type="checkbox" checked="1">126-JOSE ADRIANO DE FREITAS</label></li>
                                                                                            <li opcoes_texto_opcao="127-MARCIO ROBERTO" opcoes_valor_opcao="rca=127" opcoes_texto_botao="127" class="dropdown-item li" data-valor_opcao="rca=127" data-texto_botao="127"><label textodepois="1"><input type="checkbox" checked="1">127-MARCIO ROBERTO</label></li>
                                                                                            <li opcoes_texto_opcao="128-JOSE UBIRAJARA MENON" opcoes_valor_opcao="rca=128" opcoes_texto_botao="128" class="dropdown-item li" data-valor_opcao="rca=128" data-texto_botao="128"><label textodepois="1"><input type="checkbox" checked="1">128-JOSE UBIRAJARA MENON</label></li>
                                                                                            <li opcoes_texto_opcao="129-GIOVANNI LARA" opcoes_valor_opcao="rca=129" opcoes_texto_botao="129" class="dropdown-item li" data-valor_opcao="rca=129" data-texto_botao="129"><label textodepois="1"><input type="checkbox" checked="1">129-GIOVANNI LARA</label></li>
                                                                                            <li opcoes_texto_opcao="130-LUIZ C SCHIAVINI" opcoes_valor_opcao="rca=130" opcoes_texto_botao="130" class="dropdown-item li" data-valor_opcao="rca=130" data-texto_botao="130"><label textodepois="1"><input type="checkbox" checked="1">130-LUIZ C SCHIAVINI</label></li>
                                                                                            <li opcoes_texto_opcao="140-JACKELINE" opcoes_valor_opcao="rca=140" opcoes_texto_botao="140" class="dropdown-item li" data-valor_opcao="rca=140" data-texto_botao="140"><label textodepois="1"><input type="checkbox" checked="1">140-JACKELINE</label></li>
                                                                                            <li opcoes_texto_opcao="150-CLIENTES INATIVADOS" opcoes_valor_opcao="rca=150" opcoes_texto_botao="150" class="dropdown-item li" data-valor_opcao="rca=150" data-texto_botao="150"><label textodepois="1"><input type="checkbox" checked="1">150-CLIENTES INATIVADOS</label></li>
                                                                                            <li opcoes_texto_opcao="180-ECOMERCE" opcoes_valor_opcao="rca=180" opcoes_texto_botao="180" class="dropdown-item li" data-valor_opcao="rca=180" data-texto_botao="180"><label textodepois="1"><input type="checkbox" checked="1">180-ECOMERCE</label></li>
                                                                                            <li opcoes_texto_opcao="2-REGINALDO CASTELANI" opcoes_valor_opcao="rca=2" opcoes_texto_botao="2" class="dropdown-item li" data-valor_opcao="rca=2" data-texto_botao="2"><label textodepois="1"><input type="checkbox" checked="1">2-REGINALDO CASTELANI</label></li>
                                                                                            <li opcoes_texto_opcao="201-PATRICIA MAYRA MELO LOPES" opcoes_valor_opcao="rca=201" opcoes_texto_botao="201" class="dropdown-item li" data-valor_opcao="rca=201" data-texto_botao="201"><label textodepois="1"><input type="checkbox" checked="1">201-PATRICIA MAYRA MELO LOPES</label></li>
                                                                                            <li opcoes_texto_opcao="202-VICENTE MORENO JUNIOR" opcoes_valor_opcao="rca=202" opcoes_texto_botao="202" class="dropdown-item li" data-valor_opcao="rca=202" data-texto_botao="202"><label textodepois="1"><input type="checkbox" checked="1">202-VICENTE MORENO JUNIOR</label></li>
                                                                                            <li opcoes_texto_opcao="203-KEBIS MARCAL" opcoes_valor_opcao="rca=203" opcoes_texto_botao="203" class="dropdown-item li" data-valor_opcao="rca=203" data-texto_botao="203"><label textodepois="1"><input type="checkbox" checked="1">203-KEBIS MARCAL</label></li>
                                                                                            <li opcoes_texto_opcao="204-MARCIO DE CAMILLO" opcoes_valor_opcao="rca=204" opcoes_texto_botao="204" class="dropdown-item li" data-valor_opcao="rca=204" data-texto_botao="204"><label textodepois="1"><input type="checkbox" checked="1">204-MARCIO DE CAMILLO</label></li>
                                                                                            <li opcoes_texto_opcao="205-ALAN PIERRE GARCIA" opcoes_valor_opcao="rca=205" opcoes_texto_botao="205" class="dropdown-item li" data-valor_opcao="rca=205" data-texto_botao="205"><label textodepois="1"><input type="checkbox" checked="1">205-ALAN PIERRE GARCIA</label></li>
                                                                                            <li opcoes_texto_opcao="206-EDVALDO BISPO PACHECO" opcoes_valor_opcao="rca=206" opcoes_texto_botao="206" class="dropdown-item li" data-valor_opcao="rca=206" data-texto_botao="206"><label textodepois="1"><input type="checkbox" checked="1">206-EDVALDO BISPO PACHECO</label></li>
                                                                                            <li opcoes_texto_opcao="207-HUDSON FERNANDO ALBANEZ BARBOSA " opcoes_valor_opcao="rca=207" opcoes_texto_botao="207" class="dropdown-item li" data-valor_opcao="rca=207" data-texto_botao="207"><label textodepois="1"><input type="checkbox" checked="1">207-HUDSON FERNANDO ALBANEZ BARBOSA</label></li>
                                                                                            <li opcoes_texto_opcao="208-ANDERSON ANDREI GERALDO" opcoes_valor_opcao="rca=208" opcoes_texto_botao="208" class="dropdown-item li" data-valor_opcao="rca=208" data-texto_botao="208"><label textodepois="1"><input type="checkbox" checked="1">208-ANDERSON ANDREI GERALDO</label></li>
                                                                                            <li opcoes_texto_opcao="209-AGOSTINHO RODRIGUES PEREIRA" opcoes_valor_opcao="rca=209" opcoes_texto_botao="209" class="dropdown-item li" data-valor_opcao="rca=209" data-texto_botao="209"><label textodepois="1"><input type="checkbox" checked="1">209-AGOSTINHO RODRIGUES PEREIRA</label></li>
                                                                                            <li opcoes_texto_opcao="210-JEVERSON DA ZILVA" opcoes_valor_opcao="rca=210" opcoes_texto_botao="210" class="dropdown-item li" data-valor_opcao="rca=210" data-texto_botao="210"><label textodepois="1"><input type="checkbox" checked="1">210-JEVERSON DA ZILVA</label></li>
                                                                                            <li opcoes_texto_opcao="211-RICARDO ALMEIDA MOREIRA" opcoes_valor_opcao="rca=211" opcoes_texto_botao="211" class="dropdown-item li" data-valor_opcao="rca=211" data-texto_botao="211"><label textodepois="1"><input type="checkbox" checked="1">211-RICARDO ALMEIDA MOREIRA</label></li>
                                                                                            <li opcoes_texto_opcao="212-CARLOS ANTONIO AGUIAR" opcoes_valor_opcao="rca=212" opcoes_texto_botao="212" class="dropdown-item li" data-valor_opcao="rca=212" data-texto_botao="212"><label textodepois="1"><input type="checkbox" checked="1">212-CARLOS ANTONIO AGUIAR</label></li>
                                                                                            <li opcoes_texto_opcao="213-LUIZ ALBANO GENARO" opcoes_valor_opcao="rca=213" opcoes_texto_botao="213" class="dropdown-item li" data-valor_opcao="rca=213" data-texto_botao="213"><label textodepois="1"><input type="checkbox" checked="1">213-LUIZ ALBANO GENARO</label></li>
                                                                                            <li opcoes_texto_opcao="214-CRISTIAN FREITAS " opcoes_valor_opcao="rca=214" opcoes_texto_botao="214" class="dropdown-item li" data-valor_opcao="rca=214" data-texto_botao="214"><label textodepois="1"><input type="checkbox" checked="1">214-CRISTIAN FREITAS</label></li>
                                                                                            <li opcoes_texto_opcao="215-THIAGO OLIVEIRA DIAS" opcoes_valor_opcao="rca=215" opcoes_texto_botao="215" class="dropdown-item li" data-valor_opcao="rca=215" data-texto_botao="215"><label textodepois="1"><input type="checkbox" checked="1">215-THIAGO OLIVEIRA DIAS</label></li>
                                                                                            <li opcoes_texto_opcao="216-REINALDO PAULINO MENDES" opcoes_valor_opcao="rca=216" opcoes_texto_botao="216" class="dropdown-item li" data-valor_opcao="rca=216" data-texto_botao="216"><label textodepois="1"><input type="checkbox" checked="1">216-REINALDO PAULINO MENDES</label></li>
                                                                                            <li opcoes_texto_opcao="217-TIAGO MENEGHETTE DE MATOS" opcoes_valor_opcao="rca=217" opcoes_texto_botao="217" class="dropdown-item li" data-valor_opcao="rca=217" data-texto_botao="217"><label textodepois="1"><input type="checkbox" checked="1">217-TIAGO MENEGHETTE DE MATOS</label></li>
                                                                                            <li opcoes_texto_opcao="218-ROBSON PAULO PALHARES" opcoes_valor_opcao="rca=218" opcoes_texto_botao="218" class="dropdown-item li" data-valor_opcao="rca=218" data-texto_botao="218"><label textodepois="1"><input type="checkbox" checked="1">218-ROBSON PAULO PALHARES</label></li>
                                                                                            <li opcoes_texto_opcao="219-PEDRO AUGUSTO SOARES DE ARAUJO LOURENCO" opcoes_valor_opcao="rca=219" opcoes_texto_botao="219" class="dropdown-item li" data-valor_opcao="rca=219" data-texto_botao="219"><label textodepois="1"><input type="checkbox" checked="1">219-PEDRO AUGUSTO SOARES DE ARAUJO LOURENCO</label></li>
                                                                                            <li opcoes_texto_opcao="220-FABIO JILENO ROSSATI" opcoes_valor_opcao="rca=220" opcoes_texto_botao="220" class="dropdown-item li" data-valor_opcao="rca=220" data-texto_botao="220"><label textodepois="1"><input type="checkbox" checked="1">220-FABIO JILENO ROSSATI</label></li>
                                                                                            <li opcoes_texto_opcao="221-NAZIH DIAB AL GHADBAN" opcoes_valor_opcao="rca=221" opcoes_texto_botao="221" class="dropdown-item li" data-valor_opcao="rca=221" data-texto_botao="221"><label textodepois="1"><input type="checkbox" checked="1">221-NAZIH DIAB AL GHADBAN</label></li>
                                                                                            <li opcoes_texto_opcao="222-JUMBO-LONDRINA" opcoes_valor_opcao="rca=222" opcoes_texto_botao="222" class="dropdown-item li" data-valor_opcao="rca=222" data-texto_botao="222"><label textodepois="1"><input type="checkbox" checked="1">222-JUMBO-LONDRINA</label></li>
                                                                                            <li opcoes_texto_opcao="223-LUCIANO JOSE DA SILVA " opcoes_valor_opcao="rca=223" opcoes_texto_botao="223" class="dropdown-item li" data-valor_opcao="rca=223" data-texto_botao="223"><label textodepois="1"><input type="checkbox" checked="1">223-LUCIANO JOSE DA SILVA</label></li>
                                                                                            <li opcoes_texto_opcao="224-ADILSON APARECIDO LAZARINI" opcoes_valor_opcao="rca=224" opcoes_texto_botao="224" class="dropdown-item li" data-valor_opcao="rca=224" data-texto_botao="224"><label textodepois="1"><input type="checkbox" checked="1">224-ADILSON APARECIDO LAZARINI</label></li>
                                                                                            <li opcoes_texto_opcao="225-CASSIANA ROUBLES DOS SANTOS" opcoes_valor_opcao="rca=225" opcoes_texto_botao="225" class="dropdown-item li" data-valor_opcao="rca=225" data-texto_botao="225"><label textodepois="1"><input type="checkbox" checked="1">225-CASSIANA ROUBLES DOS SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="226-GENTIL PINHEIRO JUNIOR" opcoes_valor_opcao="rca=226" opcoes_texto_botao="226" class="dropdown-item li" data-valor_opcao="rca=226" data-texto_botao="226"><label textodepois="1"><input type="checkbox" checked="1">226-GENTIL PINHEIRO JUNIOR</label></li>
                                                                                            <li opcoes_texto_opcao="227-PAULO SERGIO GONCALVES" opcoes_valor_opcao="rca=227" opcoes_texto_botao="227" class="dropdown-item li" data-valor_opcao="rca=227" data-texto_botao="227"><label textodepois="1"><input type="checkbox" checked="1">227-PAULO SERGIO GONCALVES</label></li>
                                                                                            <li opcoes_texto_opcao="228-MAYCON - RESERVA" opcoes_valor_opcao="rca=228" opcoes_texto_botao="228" class="dropdown-item li" data-valor_opcao="rca=228" data-texto_botao="228"><label textodepois="1"><input type="checkbox" checked="1">228-MAYCON - RESERVA</label></li>
                                                                                            <li opcoes_texto_opcao="229-CARLOS ROBERTO DE SOUZA MORAES" opcoes_valor_opcao="rca=229" opcoes_texto_botao="229" class="dropdown-item li" data-valor_opcao="rca=229" data-texto_botao="229"><label textodepois="1"><input type="checkbox" checked="1">229-CARLOS ROBERTO DE SOUZA MORAES</label></li>
                                                                                            <li opcoes_texto_opcao="230-BALCAO" opcoes_valor_opcao="rca=230" opcoes_texto_botao="230" class="dropdown-item li" data-valor_opcao="rca=230" data-texto_botao="230"><label textodepois="1"><input type="checkbox" checked="1">230-BALCAO</label></li>
                                                                                            <li opcoes_texto_opcao="231-EDINHO" opcoes_valor_opcao="rca=231" opcoes_texto_botao="231" class="dropdown-item li" data-valor_opcao="rca=231" data-texto_botao="231"><label textodepois="1"><input type="checkbox" checked="1">231-EDINHO</label></li>
                                                                                            <li opcoes_texto_opcao="232-WELLINGTON FRANCISCO SIQUEIRA" opcoes_valor_opcao="rca=232" opcoes_texto_botao="232" class="dropdown-item li" data-valor_opcao="rca=232" data-texto_botao="232"><label textodepois="1"><input type="checkbox" checked="1">232-WELLINGTON FRANCISCO SIQUEIRA</label></li>
                                                                                            <li opcoes_texto_opcao="234-BRUNA ANDRESSA POLETTI" opcoes_valor_opcao="rca=234" opcoes_texto_botao="234" class="dropdown-item li" data-valor_opcao="rca=234" data-texto_botao="234"><label textodepois="1"><input type="checkbox" checked="1">234-BRUNA ANDRESSA POLETTI</label></li>
                                                                                            <li opcoes_texto_opcao="236-ALEXANDRE FERREIRA FIM" opcoes_valor_opcao="rca=236" opcoes_texto_botao="236" class="dropdown-item li" data-valor_opcao="rca=236" data-texto_botao="236"><label textodepois="1"><input type="checkbox" checked="1">236-ALEXANDRE FERREIRA FIM</label></li>
                                                                                            <li opcoes_texto_opcao="237-LUCIANO DOS SANTOS " opcoes_valor_opcao="rca=237" opcoes_texto_botao="237" class="dropdown-item li" data-valor_opcao="rca=237" data-texto_botao="237"><label textodepois="1"><input type="checkbox" checked="1">237-LUCIANO DOS SANTOS</label></li>
                                                                                            <li opcoes_texto_opcao="240-JACKELINE" opcoes_valor_opcao="rca=240" opcoes_texto_botao="240" class="dropdown-item li" data-valor_opcao="rca=240" data-texto_botao="240"><label textodepois="1"><input type="checkbox" checked="1">240-JACKELINE</label></li>
                                                                                            <li opcoes_texto_opcao="250-ALTAIR SOTANA" opcoes_valor_opcao="rca=250" opcoes_texto_botao="250" class="dropdown-item li" data-valor_opcao="rca=250" data-texto_botao="250"><label textodepois="1"><input type="checkbox" checked="1">250-ALTAIR SOTANA</label></li>
                                                                                            <li opcoes_texto_opcao="251-INATIVOS - BAIXADOS" opcoes_valor_opcao="rca=251" opcoes_texto_botao="251" class="dropdown-item li" data-valor_opcao="rca=251" data-texto_botao="251"><label textodepois="1"><input type="checkbox" checked="1">251-INATIVOS - BAIXADOS</label></li>
                                                                                            <li opcoes_texto_opcao="3-CRISTIAN  FREITAS DE LIMA FERNANDES" opcoes_valor_opcao="rca=3" opcoes_texto_botao="3" class="dropdown-item li" data-valor_opcao="rca=3" data-texto_botao="3"><label textodepois="1"><input type="checkbox" checked="1">3-CRISTIAN  FREITAS DE LIMA FERNANDES</label></li>
                                                                                            <li opcoes_texto_opcao="301-EDSON NUNES" opcoes_valor_opcao="rca=301" opcoes_texto_botao="301" class="dropdown-item li" data-valor_opcao="rca=301" data-texto_botao="301"><label textodepois="1"><input type="checkbox" checked="1">301-EDSON NUNES</label></li>
                                                                                            <li opcoes_texto_opcao="302-LUIZ SCHIAVINI MS" opcoes_valor_opcao="rca=302" opcoes_texto_botao="302" class="dropdown-item li" data-valor_opcao="rca=302" data-texto_botao="302"><label textodepois="1"><input type="checkbox" checked="1">302-LUIZ SCHIAVINI MS</label></li>
                                                                                            <li opcoes_texto_opcao="303-CARLOS LEMOS MS" opcoes_valor_opcao="rca=303" opcoes_texto_botao="303" class="dropdown-item li" data-valor_opcao="rca=303" data-texto_botao="303"><label textodepois="1"><input type="checkbox" checked="1">303-CARLOS LEMOS MS</label></li>
                                                                                            <li opcoes_texto_opcao="304-JOAO VIEIRA DO PRADO" opcoes_valor_opcao="rca=304" opcoes_texto_botao="304" class="dropdown-item li" data-valor_opcao="rca=304" data-texto_botao="304"><label textodepois="1"><input type="checkbox" checked="1">304-JOAO VIEIRA DO PRADO</label></li>
                                                                                            <li opcoes_texto_opcao="305-ADILSON DE LIMA AMERICANO" opcoes_valor_opcao="rca=305" opcoes_texto_botao="305" class="dropdown-item li" data-valor_opcao="rca=305" data-texto_botao="305"><label textodepois="1"><input type="checkbox" checked="1">305-ADILSON DE LIMA AMERICANO</label></li>
                                                                                            <li opcoes_texto_opcao="306-ARISTEU PADILHA DO AMARAL" opcoes_valor_opcao="rca=306" opcoes_texto_botao="306" class="dropdown-item li" data-valor_opcao="rca=306" data-texto_botao="306"><label textodepois="1"><input type="checkbox" checked="1">306-ARISTEU PADILHA DO AMARAL</label></li>
                                                                                            <li opcoes_texto_opcao="307-LUCIANO PEREIRA" opcoes_valor_opcao="rca=307" opcoes_texto_botao="307" class="dropdown-item li" data-valor_opcao="rca=307" data-texto_botao="307"><label textodepois="1"><input type="checkbox" checked="1">307-LUCIANO PEREIRA</label></li>
                                                                                            <li opcoes_texto_opcao="308-ABRAO CARLOS PEIXOTO" opcoes_valor_opcao="rca=308" opcoes_texto_botao="308" class="dropdown-item li" data-valor_opcao="rca=308" data-texto_botao="308"><label textodepois="1"><input type="checkbox" checked="1">308-ABRAO CARLOS PEIXOTO</label></li>
                                                                                            <li opcoes_texto_opcao="309-GILBERTO DA SILVA" opcoes_valor_opcao="rca=309" opcoes_texto_botao="309" class="dropdown-item li" data-valor_opcao="rca=309" data-texto_botao="309"><label textodepois="1"><input type="checkbox" checked="1">309-GILBERTO DA SILVA</label></li>
                                                                                            <li opcoes_texto_opcao="310-DARBEM FILHO REP. COMERCIAIS" opcoes_valor_opcao="rca=310" opcoes_texto_botao="310" class="dropdown-item li" data-valor_opcao="rca=310" data-texto_botao="310"><label textodepois="1"><input type="checkbox" checked="1">310-DARBEM FILHO REP. COMERCIAIS</label></li>
                                                                                            <li opcoes_texto_opcao="311-REGINALDO RAMOS" opcoes_valor_opcao="rca=311" opcoes_texto_botao="311" class="dropdown-item li" data-valor_opcao="rca=311" data-texto_botao="311"><label textodepois="1"><input type="checkbox" checked="1">311-REGINALDO RAMOS</label></li>
                                                                                            <li opcoes_texto_opcao="312-DIOGO DE MEDEIROS FIGUEREDO LTDA" opcoes_valor_opcao="rca=312" opcoes_texto_botao="312" class="dropdown-item li" data-valor_opcao="rca=312" data-texto_botao="312"><label textodepois="1"><input type="checkbox" checked="1">312-DIOGO DE MEDEIROS FIGUEREDO LTDA</label></li>
                                                                                            <li opcoes_texto_opcao="333-JUMBO-CASCAVEL" opcoes_valor_opcao="rca=333" opcoes_texto_botao="333" class="dropdown-item li" data-valor_opcao="rca=333" data-texto_botao="333"><label textodepois="1"><input type="checkbox" checked="1">333-JUMBO-CASCAVEL</label></li>
                                                                                            <li opcoes_texto_opcao="4-PIRES" opcoes_valor_opcao="rca=4" opcoes_texto_botao="4" class="dropdown-item li" data-valor_opcao="rca=4" data-texto_botao="4"><label textodepois="1"><input type="checkbox" checked="1">4-PIRES</label></li>
                                                                                            <li opcoes_texto_opcao="6-LUIZ SCHIAVINI" opcoes_valor_opcao="rca=6" opcoes_texto_botao="6" class="dropdown-item li" data-valor_opcao="rca=6" data-texto_botao="6"><label textodepois="1"><input type="checkbox" checked="1">6-LUIZ SCHIAVINI</label></li>
                                                                                            </ul>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="div_opcao_controles_btns_img col-md-auto w-auto"></div>
                                                                                </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="div_periodos accordion-item" titulo="Data de Transmissao" target="#periodos" aberto="1">
                                                                <div class="accordion-header" titulo="Data de Transmissao" target="#periodos" aberto="1">
                                                                    <div data-bs-toggle="collapse" data-bs-target="#periodos" aberto="1" class="accordion-button" type="button" aria-expanded="true" aria-controls="periodos">Data de Transmissao</div>
                                                                </div>
                                                                <div id="periodos" class="collapse show">
                                                                    <div class="accordion-body" aberto="1">
                                                                    <div class="row">
                                                                        <div class="col-auto mt-2 div_periodo col">
                                                                            <div dtini="2022-01-01" dtfim="2022-01-24" funcao_inclusao="window.fnsisjd.inserir_periodo_pesquisa({elemento:this})" funcao_exclusao="window.fnsisjd.deletar_controles({elemento:this})" class="card">
                                                                                <div class="card-header">Periodo 01</div>
                                                                                <div class="card-body">
                                                                                <div class="row">
                                                                                    <div class="col">
                                                                                        <div class="row">
                                                                                            <div class="col-auto col"><input type="date" class="componente_data" value="2022-01-01"></div>
                                                                                            <div class="col-auto col"><input type="date" class="componente_data" value="2022-01-24"></div>
                                                                                        </div>
                                                                                        <div class="align-items-center row">
                                                                                            <div class="col">
                                                                                            <div class="w-100 text-center"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/JAN.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/FEV.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/MAR.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/ABR.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/MAI.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/JUN.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/JUL.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/AGO.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/SET.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/OUT.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/NOV.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><img class="imagem_mes_calendario item_destaque100pct_hover" title="Preenche as datas com este mes inteiro" src="/sjd/images/calendario/DEZ.png" onclick="window.fnhtml.fncal.clicou_mes_calendario({elemento:this})"><input type="number" class="inputano" value="2021" title="Ano para preenchimento do mes inteiro" step="1" min="0"></div>
                                                                                            </div>
                                                                                        </div>
                                                                                    </div>
                                                                                    <div class="div_opcao_controles_btns_img col-md-auto w-auto"></div>
                                                                                </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="div_botao_pesquisar d-grid gap-2 col-6 mx-auto mt-3"><button class="botao_pesquisar btn btn-primary" value="Pesquisar" data-visao="entregas" onclick="window.fnsisjd.pesquisar_dados(this)">Pesquisar</button></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="div_resultado_l2 row">
                                    <div class="div_resultado col"></div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
         </div>
      </div>
   </main>
</body>
<script type="module">
    import { fndt } from "/sjd/javascript/modulos/classes/data/FuncoesData.js";
    $("input.componente_data").eq(0).val(fndt.dataUSA(fndt.data_primeirodiames()));
    $("input.componente_data").eq(1).val(fndt.dataUSA(fndt.hoje()));
    $("input.inputano").val(fndt.dataBR_getAno(fndt.data_primeirodiames()));
</script>
</html>